import type {
  Program,
  AgeGroup,
  Badge,
  CoachDashboardData,
  StudentDashboardData,
} from '@/types';

// ─── Age Groups ──────────────────────────────────────────────────
export const AGE_GROUPS: AgeGroup[] = [
  { id: '4-5',   label: 'Ages 4–5',   emoji: '🌱', description: 'Tiny Engineers – first steps into technology' },
  { id: '6-7',   label: 'Ages 6–7',   emoji: '🚀', description: 'Explorers – hands-on building and simple coding' },
  { id: '8-9',   label: 'Ages 8–9',   emoji: '⚙️',  description: 'Builders – sensors, logic, and real projects' },
  { id: '10-12', label: 'Ages 10–12', emoji: '🤖', description: 'Innovators – advanced robotics and programming' },
  { id: '13-15', label: 'Ages 13–15', emoji: '💡', description: 'Engineers – AI, IoT, web development, and competitions' },
];

// ─── All 26 Programs ─────────────────────────────────────────────
export const PROGRAMS: Program[] = [
  // ── Young Learners ──
  {
    id: 'wedo',
    slug: 'wedo',
    title: 'WeDo',
    description: 'LEGO-based hands-on robotics for beginners. Build models and bring them to life with simple programming.',
    icon: '🧱',
    color: '#F97316',
    bgColor: '#FFF7ED',
    textColor: '#C2410C',
    category: 'robotics',
    ageGroups: ['6-7', '8-9'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 3,
    lessonCount: 24,
    tags: ['LEGO', 'Building', 'Sensors', 'Motors'],
  },
  {
    id: 'early-simple-machines',
    slug: 'early-simple-machines',
    title: 'Early Simple Machines',
    shortTitle: 'Simple Machines',
    description: 'Discover levers, wheels, gears, and pulleys through fun building challenges for the youngest engineers.',
    icon: '⚙️',
    color: '#F59E0B',
    bgColor: '#FFFBEB',
    textColor: '#B45309',
    category: 'robotics',
    ageGroups: ['4-5', '6-7'],
    levels: ['Beginner'],
    courseCount: 2,
    lessonCount: 16,
    tags: ['Gears', 'Levers', 'Pulleys', 'Physics'],
  },
  {
    id: 'codey-rocky',
    slug: 'codey-rocky',
    title: 'Codey Rocky',
    description: 'A cute programmable robot that introduces AI concepts and block-based coding for young learners.',
    icon: '🤖',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    textColor: '#1D4ED8',
    category: 'robotics',
    ageGroups: ['6-7', '8-9'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 2,
    lessonCount: 18,
    tags: ['Makeblock', 'Block Coding', 'AI Basics', 'Sensors'],
  },
  {
    id: 'mtiny',
    slug: 'mtiny',
    title: 'mTiny',
    description: 'A screen-free coding robot with a tap-and-play coding map, perfect for pre-readers and kindergarten.',
    icon: '🐣',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    textColor: '#BE185D',
    category: 'robotics',
    ageGroups: ['4-5', '6-7'],
    levels: ['Beginner'],
    courseCount: 1,
    lessonCount: 10,
    tags: ['Screen-free', 'Sequences', 'Loops', 'Early Learning'],
  },
  {
    id: 'scratch-jr',
    slug: 'scratch-jr',
    title: 'Scratch Jr',
    description: 'Visual block coding on tablets where kids create their own interactive stories and simple games.',
    icon: '🐱',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    textColor: '#6D28D9',
    category: 'coding',
    ageGroups: ['4-5', '6-7'],
    levels: ['Beginner'],
    courseCount: 2,
    lessonCount: 16,
    tags: ['Visual Coding', 'Stories', 'Animation', 'iPad'],
  },
  {
    id: 'scratch',
    slug: 'scratch',
    title: 'Scratch',
    description: 'The world\'s most popular visual programming language. Build games, animations, and interactive stories.',
    icon: '🐱',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    textColor: '#5B21B6',
    category: 'coding',
    ageGroups: ['8-9', '10-12'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 11,
    tags: ['Visual Coding', 'Games', 'Animation', 'Events'],
  },

  // ── Mid Level ──
  {
    id: 'ev3',
    slug: 'ev3',
    title: 'EV3',
    shortTitle: 'LEGO EV3',
    description: 'LEGO Mindstorms EV3 — the classic competition robot. Build, program, and compete with powerful sensors and motors.',
    icon: '🦾',
    color: '#EF4444',
    bgColor: '#FEF2F2',
    textColor: '#B91C1C',
    category: 'robotics',
    ageGroups: ['10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 3,
    lessonCount: 30,
    tags: ['LEGO', 'Competition', 'Sensors', 'PID Control'],
  },
  {
    id: 'spike-prime',
    slug: 'spike-prime',
    title: 'Spike Prime',
    shortTitle: 'Spike Prime',
    description: 'LEGO Education Spike Prime — next-generation robotics with Python support, perfect for FLL and competitions.',
    icon: '⚡',
    color: '#F97316',
    bgColor: '#FFF7ED',
    textColor: '#C2410C',
    category: 'robotics',
    ageGroups: ['10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 13,
    tags: ['LEGO', 'Building', 'Video', 'FLL'],
  },
  {
    id: 'microbit',
    slug: 'microbit',
    title: 'micro:bit',
    description: 'A pocket-sized microcontroller that teaches physical computing, coding, and electronics in one device.',
    icon: '💻',
    color: '#10B981',
    bgColor: '#ECFDF5',
    textColor: '#047857',
    category: 'electronics',
    ageGroups: ['8-9', '10-12'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 3,
    lessonCount: 24,
    tags: ['BBC', 'Sensors', 'Display', 'MakeCode'],
  },
  {
    id: 'makey-makey',
    slug: 'makey-makey',
    title: 'Makey Makey',
    description: 'Turn everyday objects into touchpads. Connect bananas, pencil drawings, or Play-Doh to your computer.',
    icon: '🎮',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    textColor: '#0E7490',
    category: 'electronics',
    ageGroups: ['8-9', '10-12'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 11,
    tags: ['Invention', 'Creativity', 'Conductivity', 'Scratch'],
  },
  {
    id: 'mbot2',
    slug: 'mbot2',
    title: 'mBot2',
    description: 'Advanced educational robot from Makeblock with Scratch and Python support, perfect for intermediate students.',
    icon: '🤖',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    textColor: '#1E40AF',
    category: 'robotics',
    ageGroups: ['10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 3,
    lessonCount: 26,
    tags: ['Makeblock', 'Python', 'Sensors', 'Autonomous'],
  },

  // ── Advanced ──
  {
    id: 'arduino',
    slug: 'arduino',
    title: 'Arduino',
    description: 'The industry-standard open-source electronics platform. Build real-world circuits and program them in C++.',
    icon: '🔌',
    color: '#0D9488',
    bgColor: '#F0FDFA',
    textColor: '#0F766E',
    category: 'electronics',
    ageGroups: ['13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 3,
    lessonCount: 28,
    tags: ['C++', 'Circuits', 'Sensors', 'IoT'],
  },
  {
    id: 'electronics',
    slug: 'electronics',
    title: 'Electronics',
    description: 'Hands-on, no-solder circuits: build paper circuits and stitch wearable e-textiles with sewable LEDs. Learn complete circuits, polarity and switches.',
    icon: '⚡',
    color: '#EAB308',
    bgColor: '#FEFCE8',
    textColor: '#A16207',
    category: 'electronics',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 1,
    lessonCount: 2,
    tags: ['Circuits', 'Paper Circuits', 'E-textiles', 'Wearables'],
  },
  {
    id: 'ai-ml-iot',
    slug: 'ai-ml-iot',
    title: 'AI / ML / IoT',
    shortTitle: 'AI & IoT',
    description: 'Explore artificial intelligence, machine learning, and the Internet of Things — the technologies shaping tomorrow.',
    icon: '🧠',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    textColor: '#5B21B6',
    category: 'advanced',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 1,
    lessonCount: 7,
    tags: ['AI', 'Machine Learning', 'CreateAI', 'Data'],
  },
  {
    id: 'drones',
    slug: 'drones',
    title: 'Drones',
    description: 'Program a real Tello EDU drone: fly safely, code autonomous flights with DroneBlocks, navigate mission pads, then go to Python and a multi-drone swarm.',
    icon: '🚁',
    color: '#475569',
    bgColor: '#F8FAFC',
    textColor: '#334155',
    category: 'advanced',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 12,
    tags: ['Tello EDU', 'DroneBlocks', 'Python', 'Mission Pads', 'Swarm'],
  },
  {
    id: 'vr',
    slug: 'vr',
    title: 'VR',
    shortTitle: 'Virtual Reality',
    description: 'Build and explore your own virtual worlds with CoSpaces Edu — 3D scenes, CoBlocks coding, physics and 360 tours — viewed in VR on Meta Quest headsets.',
    icon: '🥽',
    color: '#0EA5E9',
    bgColor: '#F0F9FF',
    textColor: '#0369A1',
    category: 'advanced',
    ageGroups: ['13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 12,
    tags: ['CoSpaces Edu', 'CoBlocks', 'Meta Quest', '360 / AR'],
  },
  {
    id: '3d-modeling',
    slug: '3d-modeling',
    title: '3D Modeling',
    description: 'Design objects in 3D using tools like Tinkercad. From simple shapes to complex engineering designs.',
    icon: '🎨',
    color: '#D97706',
    bgColor: '#FFFBEB',
    textColor: '#B45309',
    category: 'design',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate'],
    courseCount: 2,
    lessonCount: 16,
    tags: ['Tinkercad', 'Design', 'CAD', 'Engineering'],
  },
  {
    id: '3d-printing',
    slug: '3d-printing',
    title: '3D Printing',
    description: 'Go from digital design to physical object with Tinkercad: design printable models, export STL, slice in Cura, print safely, and iterate.',
    icon: '🖨️',
    color: '#9333EA',
    bgColor: '#FAF5FF',
    textColor: '#7E22CE',
    category: 'design',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 12,
    tags: ['Tinkercad', 'Slicing (Cura)', 'FDM', 'Tolerances'],
  },
  {
    id: 'game-design',
    slug: 'game-design',
    title: 'Game Design',
    description: 'Design and build real video games in MakeCode Arcade — sprites, tilemaps, projectiles, multiplayer — then code in JavaScript/Python and share your creations.',
    icon: '🎮',
    color: '#DC2626',
    bgColor: '#FEF2F2',
    textColor: '#991B1B',
    category: 'design',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 12,
    tags: ['MakeCode Arcade', 'Sprites & Tilemaps', 'Multiplayer', 'JavaScript/Python'],
  },

  // ── Coding Languages ──
  {
    id: 'python',
    slug: 'python',
    title: 'Python',
    description: 'Beginner-friendly text coding — variables, loops, functions — then MicroPython on the micro:bit and ESP32 for real physical-computing and IoT projects.',
    icon: '🐍',
    color: '#1D4ED8',
    bgColor: '#EFF6FF',
    textColor: '#1E40AF',
    category: 'coding',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 6,
    tags: ['Text Coding', 'MicroPython', 'micro:bit', 'ESP32 / IoT'],
  },
  {
    id: 'small-basic',
    slug: 'small-basic',
    title: 'Small Basic',
    shortTitle: 'Small Basic',
    description: 'Microsoft Small Basic — a simple, friendly first step into text-based coding. Learn the editor, variables, input/output and calculations.',
    icon: '💠',
    color: '#0EA5E9',
    bgColor: '#F0F9FF',
    textColor: '#0369A1',
    category: 'coding',
    ageGroups: ['13-15'],
    levels: ['Beginner'],
    courseCount: 1,
    lessonCount: 2,
    tags: ['Text Coding', 'Variables', 'Beginner'],
  },
  {
    id: 'html-css-js',
    slug: 'html-css-js',
    title: 'HTML / CSS / JavaScript',
    shortTitle: 'Web Dev',
    description: 'Build real websites from scratch. HTML structure, CSS styling, and JavaScript interactivity.',
    icon: '🌐',
    color: '#EA580C',
    bgColor: '#FFF7ED',
    textColor: '#C2410C',
    category: 'coding',
    ageGroups: ['10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 11,
    tags: ['Web', 'HTML', 'CSS', 'JavaScript'],
  },
  {
    id: 'php-mysql',
    slug: 'php-mysql',
    title: 'PHP / MySQL',
    description: 'Server-side web development with databases. Build dynamic websites that store and retrieve data.',
    icon: '🗄️',
    color: '#4F46E5',
    bgColor: '#EEF2FF',
    textColor: '#3730A3',
    category: 'coding',
    ageGroups: ['13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 15,
    tags: ['Backend', 'Database', 'CRUD', 'Web Dev'],
  },

  // ── Special Programs ──
  {
    id: 'projects',
    slug: 'projects',
    title: 'Projects',
    description: 'Real-world interdisciplinary projects combining multiple skills. Design, build, test, and present.',
    icon: '🏗️',
    color: '#0F766E',
    bgColor: '#F0FDFA',
    textColor: '#0F766E',
    category: 'projects',
    ageGroups: ['6-7', '8-9', '10-12', '13-15'],
    levels: ['Beginner', 'Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 8,
    tags: ['Interdisciplinary', 'Design Thinking', 'Teamwork', 'Presentation'],
  },
  {
    id: 'makex',
    slug: 'makex',
    title: 'MakeX Preparation',
    shortTitle: 'MakeX',
    description: 'Official MakeX competition training. Rules, strategy, robot design, programming, and team coordination.',
    icon: '🏆',
    color: '#B45309',
    bgColor: '#FFFBEB',
    textColor: '#92400E',
    category: 'competition',
    ageGroups: ['10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 4,
    tags: ['Competition', 'Strategy', 'MakeX', 'Team'],
  },
  {
    id: 'competition',
    slug: 'competition',
    title: 'Competition Training',
    description: 'Develop the skills to win: time management, stress testing, troubleshooting under pressure, and presenting.',
    icon: '🥇',
    color: '#DC2626',
    bgColor: '#FEF2F2',
    textColor: '#991B1B',
    category: 'competition',
    ageGroups: ['8-9', '10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 4,
    tags: ['Strategy', 'Practice', 'Presentation', 'Teamwork'],
  },
  {
    id: 'invention',
    slug: 'invention',
    title: 'Invention & Innovation',
    description: 'Design thinking, problem identification, prototyping, and pitching original invention ideas.',
    icon: '💡',
    color: '#6D28D9',
    bgColor: '#F5F3FF',
    textColor: '#5B21B6',
    category: 'projects',
    ageGroups: ['10-12', '13-15'],
    levels: ['Intermediate', 'Advanced'],
    courseCount: 1,
    lessonCount: 8,
    tags: ['Design Thinking', 'Innovation', 'Prototype', 'Pitch'],
  },
];

// ─── Badges ──────────────────────────────────────────────────────
export const BADGES: Badge[] = [
  { id: 'first-lesson',      name: 'First Steps',        description: 'Completed your first lesson!',              icon: '👟', color: '#10B981', category: 'progress' },
  { id: 'week-streak',       name: '7-Day Streak',        description: 'Showed up 7 sessions in a row!',            icon: '🔥', color: '#F97316', category: 'progress' },
  { id: 'quiz-master',       name: 'Quiz Master',         description: 'Scored 100% on a quiz.',                    icon: '🎯', color: '#7C3AED', category: 'skill' },
  { id: 'first-robot',       name: 'Robot Builder',       description: 'Built your first working robot!',           icon: '🤖', color: '#2563EB', category: 'achievement' },
  { id: 'coder',             name: 'Coder',               description: 'Wrote your first program.',                 icon: '💻', color: '#059669', category: 'skill' },
  { id: 'innovator',         name: 'Innovator',           description: 'Submitted an original invention project.',  icon: '💡', color: '#D97706', category: 'achievement' },
  { id: 'team-player',       name: 'Team Player',         description: 'Completed a team challenge.',               icon: '🤝', color: '#0EA5E9', category: 'achievement' },
  { id: 'competition-ready', name: 'Competition Ready',   description: 'Completed competition training.',           icon: '🏆', color: '#B45309', category: 'competition' },
  { id: 'bug-squasher',      name: 'Bug Squasher',        description: 'Fixed a bug all by yourself!',              icon: '🐛', color: '#EF4444', category: 'skill' },
  { id: 'designer',          name: 'Designer',            description: 'Finished a 3D modeling project.',           icon: '🎨', color: '#EC4899', category: 'skill' },
  { id: 'ai-explorer',       name: 'AI Explorer',         description: 'Completed the AI/ML introduction.',         icon: '🧠', color: '#6D28D9', category: 'skill' },
  { id: 'makex-champion',    name: 'MakeX Champion',      description: 'Participated in a MakeX competition.',      icon: '🥇', color: '#EAB308', category: 'competition' },
];

// ─── Mock Coach Dashboard Data ────────────────────────────────────
export const COACH_DASHBOARD: CoachDashboardData = {
  coachName: 'Coach Ahmed',
  todayLessons: [
    {
      id: 'tl-1',
      lessonId: 'scratch-jr-lesson-1',
      title: 'Welcome to Scratch Jr!',
      programTitle: 'Scratch Jr',
      programColor: '#8B5CF6',
      group: 'Explorers A (Ages 6–7)',
      time: '09:00 AM',
      duration: '45 min',
      ageGroup: '6-7',
    },
    {
      id: 'tl-2',
      lessonId: 'mbot2-lesson-3',
      title: 'Line Following with mBot2',
      programTitle: 'mBot2',
      programColor: '#2563EB',
      group: 'Innovators B (Ages 10–12)',
      time: '11:00 AM',
      duration: '60 min',
      ageGroup: '10-12',
    },
    {
      id: 'tl-3',
      lessonId: 'python-lesson-5',
      title: 'Functions and Return Values',
      programTitle: 'Python',
      programColor: '#1D4ED8',
      group: 'Engineers A (Ages 13–15)',
      time: '02:00 PM',
      duration: '90 min',
      ageGroup: '13-15',
    },
  ],
  recentLessons: [
    { id: 'rl-1', title: 'My First Character',     order: 2, duration: '45 min', difficulty: 1, skills: ['Sequencing'], programTitle: 'Scratch Jr', programColor: '#8B5CF6', completedDate: 'Yesterday' },
    { id: 'rl-2', title: 'Move and Turn',           order: 3, duration: '45 min', difficulty: 2, skills: ['Loops'],       programTitle: 'Scratch Jr', programColor: '#8B5CF6', completedDate: '2 days ago' },
    { id: 'rl-3', title: 'Sensor Introduction',     order: 1, duration: '60 min', difficulty: 2, skills: ['Sensors'],    programTitle: 'mBot2',     programColor: '#2563EB',  completedDate: '3 days ago' },
    { id: 'rl-4', title: 'Variables and Data Types',order: 4, duration: '60 min', difficulty: 3, skills: ['Variables'],  programTitle: 'Python',    programColor: '#1D4ED8',  completedDate: '4 days ago' },
  ],
  stats: {
    totalStudents: 47,
    completedThisWeek: 8,
    totalLessons: 120,
    completedLessons: 34,
  },
  groups: [
    { id: 'g1', name: 'Explorers A',  ageGroup: '6-7',   studentCount: 10, currentCourse: 'Scratch Jr – Beginners', schedule: 'Sat 9:00–9:45 AM' },
    { id: 'g2', name: 'Builders B',   ageGroup: '8-9',   studentCount: 12, currentCourse: 'micro:bit – Level 1',    schedule: 'Sat 10:00–11:00 AM' },
    { id: 'g3', name: 'Innovators C', ageGroup: '10-12', studentCount: 13, currentCourse: 'mBot2 – Intermediate',   schedule: 'Sat 11:00 AM–12:00 PM' },
    { id: 'g4', name: 'Engineers A',  ageGroup: '13-15', studentCount: 12, currentCourse: 'Python – Intermediate',  schedule: 'Sat 2:00–3:30 PM' },
  ],
};

// ─── Mock Student Dashboard Data ─────────────────────────────────
export const STUDENT_DASHBOARD: StudentDashboardData = {
  studentName: 'Omar',
  currentProgram: 'Scratch Jr',
  currentProgramColor: '#8B5CF6',
  nextLesson: { id: 'scratch-jr-lesson-3', title: 'Let\'s Move!', duration: '45 min' },
  progress: 25,
  missionPoints: 320,
  badges: [
    { id: 'first-lesson', name: 'First Steps',   icon: '👟', color: '#10B981', category: 'progress', description: '', earned: true, earnedDate: '2 weeks ago' },
    { id: 'coder',        name: 'Coder',          icon: '💻', color: '#059669', category: 'skill',    description: '', earned: true, earnedDate: '1 week ago'  },
    { id: 'team-player',  name: 'Team Player',    icon: '🤝', color: '#0EA5E9', category: 'achievement', description: '', earned: true, earnedDate: 'Yesterday'  },
  ],
  recentActivity: [
    { lessonTitle: 'My First Character', date: 'Yesterday',   score: 90 },
    { lessonTitle: 'Welcome to Scratch Jr!', date: '1 week ago', score: 100 },
  ],
};

// ─── Helper Functions ─────────────────────────────────────────────
export function getProgramBySlug(slug: string): Program | undefined {
  return PROGRAMS.find(p => p.slug === slug);
}

export function getProgramsByAgeGroup(ageGroup: string): Program[] {
  return PROGRAMS.filter(p => p.ageGroups.includes(ageGroup as import('@/types').AgeGroupId));
}

export function getProgramsByCategory(category: string): Program[] {
  if (category === 'all') return PROGRAMS;
  return PROGRAMS.filter(p => p.category === category);
}

export const PROGRAM_CATEGORIES = [
  { id: 'all',         label: 'All Programs',   emoji: '🌟' },
  { id: 'robotics',    label: 'Robotics',        emoji: '🤖' },
  { id: 'coding',      label: 'Coding',          emoji: '💻' },
  { id: 'electronics', label: 'Electronics',     emoji: '⚡' },
  { id: 'design',      label: 'Design & Making', emoji: '🎨' },
  { id: 'advanced',    label: 'Advanced Tech',   emoji: '🧠' },
  { id: 'competition', label: 'Competition',     emoji: '🏆' },
  { id: 'projects',    label: 'Projects',        emoji: '🏗️' },
];
