import type { Course, LessonDetail } from '@/types';

// ════════════════════════════════════════════════════════════════
//  mBot2 / CyberPi — "Coding & IoT, Part 1"
//  Converted from RoboHolic Summer Camp 2025 materials
//  (9-12 yo → Mbot2 Activities Part 1). Lesson plans by Makeblock.
// ════════════════════════════════════════════════════════════════
export const MBOT2_COURSE: Course = {
  id: 'mbot2-iot-1',
  slug: 'coding-and-iot-part-1',
  title: 'mBot2 Coding & IoT — Part 1',
  programId: 'mbot2',
  programSlug: 'mbot2',
  ageGroup: '10-12',
  level: 'Intermediate',
  description:
    'Students use the CyberPi controller and mBlock to build real smart devices — from a noise detector to a houseplant carer and a self-driving vehicle. Each project follows the 5E model (Engage, Explore, Explain, Elaborate, Evaluate) and connects coding to everyday life.',
  objectives: [
    'Use CyberPi sensors to retrieve real-world data',
    'Display data and feedback on the CyberPi screen and LEDs',
    'Use variables, conditionals, and broadcasts in mBlock',
    'Connect computing concepts to real-life problems',
    'Design, build, test, and present a working smart device',
  ],
  duration: '14 sessions × 45 minutes',
  totalHours: 10.5,
  lessonCount: 14,
  prerequisites: ['Comfortable with block-based coding', 'Basic knowledge of sensors'],
  skills: ['Sensors & Data', 'Variables', 'Conditionals', 'IoT Thinking', 'Problem Solving'],
  modules: [
    {
      id: 'mb2-m1',
      title: 'Module 1: Sensing the World',
      description: 'Read sensor data and respond to the environment.',
      order: 1,
      lessons: [
        { id: 'mbot2-l1', title: 'Noise Detector',          duration: '45 min', difficulty: 2, skills: ['Sound Sensor', 'Data', 'Conditionals'], order: 1 },
        { id: 'mbot2-l2', title: 'Voice Reactive Lights',    duration: '45 min', difficulty: 2, skills: ['Sound Sensor', 'LEDs', 'Mapping'],      order: 2 },
        { id: 'mbot2-l3', title: 'Remote Classroom Polling', duration: '45 min', difficulty: 3, skills: ['Wireless', 'Broadcast', 'Data'],        order: 3 },
        { id: 'mbot2-l4', title: 'Houseplant Care',          duration: '45 min', difficulty: 3, skills: ['Sensors', 'Thresholds', 'IoT'],         order: 4 },
      ],
    },
    {
      id: 'mb2-m2',
      title: 'Module 2: Smart Devices',
      description: 'Build devices that make decisions and notify people.',
      order: 2,
      lessons: [
        { id: 'mbot2-l5', title: 'Smart Notifier',     duration: '45 min', difficulty: 3, skills: ['Notifications', 'Logic'],       order: 5 },
        { id: 'mbot2-l6', title: 'Parcel Locker',       duration: '45 min', difficulty: 3, skills: ['Passwords', 'Security', 'Logic'], order: 6 },
        { id: 'mbot2-l7', title: 'Intelligent Vehicles', duration: '45 min', difficulty: 4, skills: ['Motors', 'Autonomy', 'Sensors'], order: 7 },
        { id: 'mbot2-l8', title: 'Bus Tracker',         duration: '45 min', difficulty: 3, skills: ['Real-time Data', 'Display'],     order: 8 },
      ],
    },
    {
      id: 'mb2-m3',
      title: 'Module 3: Games & Interaction',
      description: 'Use sensors and the screen to build interactive games.',
      order: 3,
      lessons: [
        { id: 'mbot2-l9',  title: 'Colors Hunter',            duration: '45 min', difficulty: 3, skills: ['Color Sensor', 'Game Logic'], order: 9 },
        { id: 'mbot2-l10', title: 'Opposite Game',            duration: '45 min', difficulty: 3, skills: ['Logic', 'Reaction'],          order: 10 },
        { id: 'mbot2-l11', title: 'Catch Fish Carnival I',    duration: '45 min', difficulty: 4, skills: ['Game Design', 'Variables'],   order: 11 },
        { id: 'mbot2-l12', title: 'Catch Fish Carnival II',   duration: '45 min', difficulty: 4, skills: ['Game Design', 'Scoring'],     order: 12 },
        { id: 'mbot2-l13', title: 'Dodge the Bird I',         duration: '45 min', difficulty: 4, skills: ['Game Loop', 'Collision'],     order: 13 },
        { id: 'mbot2-l14', title: 'Dodge the Bird II',        duration: '45 min', difficulty: 5, skills: ['Game Polish', 'Levels'],      order: 14 },
      ],
    },
  ],
};

// ─── Lesson 1: Noise Detector — Full Detail ──────────────────────
// Source: "Lesson 01_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_1: LessonDetail = {
  id: 'mbot2-l1',
  slug: 'noise-detector',
  title: 'Noise Detector',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 2,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Sound Sensor', 'Data & Variables', 'Conditionals', 'LEDs & Screen', 'IoT Thinking'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                          quantity: '1 per student or pair' },
    { item: 'Pens and paper (for the survey)',      quantity: '1 per student' },
    { item: 'Visual Aids slides (projector)',       quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Identify the basic characteristics and types of data.',
    'Explain the importance and common uses of data in everyday life.',
    'Use a sensor to retrieve data and display it on the screen.',
    'Write a program that creates a working noise detector.',
  ],
  assessmentChecklist: [
    'Student can give examples of different types of data (images, sounds, text, numbers).',
    'Student connected CyberPi to mBlock and read the sound-volume sensor.',
    'Student stored the volume in a variable and displayed it on the screen.',
    'Student used a conditional + threshold to trigger an alert (red LEDs + "Please be quiet").',
    'Student described a real situation where a noise detector would be useful.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Install mBlock on each laptop and confirm it connects to a CyberPi (USB or Bluetooth).',
        'Charge / check every CyberPi kit. Have at least one spare ready.',
        'Open the "Lesson 01 Visual Aids" slides on the projector — the lesson refers to specific slides.',
        'Build the finished Noise Detector yourself first so you can demo it and anticipate issues.',
        'Print or prepare pens & paper for the opening in-class survey.',
        'Prerequisites to keep in mind: students should already be comfortable with block-based coding and the basic idea of a sensor.',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–8: Hand out pens & paper; students work in pairs and survey classmates with 3 questions (e.g. "Where would you like to spend your weekends?", "How many times do you visit the library per month?", "Have you seen any uncivil behaviour?"). Give 1 minute, then pick 2–3 pairs to share.',
          tip: 'Then ask "What is data?" Explain that all those answers ARE data — data is distinct information (birthday, height, hobby…) that comes as images, sounds, text, symbols and numbers.',
          coachNote: 'Goal of this section: students feel that data is everywhere and useful — don\'t rush to the robot yet.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 10–11: Introduce a scenario where noise is annoying — e.g. "You\'re on a bus and someone is talking very loudly. How do you feel?" Then: "Imagine a device that monitors the sound around us. What features must it have?" Pairs discuss 1 minute; pick 2 students to share.',
          tip: 'Write the suggested features on the board — you\'ll turn them into a mind map next.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 13–16: Show how a noise detector works. Together with the class, analyse the features it needs and draw a mind map (detect sound → decide if too loud → warn).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 18–28: Show where the modules are on CyberPi (LED screen, buttons, joystick, sensors, LED indicators). Help students start CyberPi, connect it in mBlock, and add the CyberPi device. Then build the program in stages — see the Main Activity below.',
          coachNote: 'This is the heart of the lesson. Move through it in small steps and let students test after each stage.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 30–31: Pick 1–2 students to demo their noise detector. Discuss: "Where would a noise detector be useful? When should we watch our own volume?" Finish with: "What other uses of data can you think of in daily life?"',
          tip: 'Tie it back to the opening survey — bring the lesson full circle from data → device → real life.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Noise Detector! 🔊',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Noise Detector! 🔊',
      content: [
        'Do the quick class survey with your partner — you\'re collecting DATA!',
        'Connect your CyberPi to mBlock.',
        'Use the sound sensor to read the volume around you.',
        'Show the volume number on the CyberPi screen.',
        'Make a rule: if it gets too loud, flash red LEDs and show "Please be quiet".',
        'Test it — shout, clap, whisper. Does it react?',
        'Show your detector to the class!',
      ] as string[],
      studentContent: [
        '📋 Collect data with the class survey',
        '🔌 Connect CyberPi to mBlock',
        '🎤 Read the sound volume with the sensor',
        '🖥️ Show the volume on the screen',
        '🚨 If too loud → red LEDs + "Please be quiet"',
        '🧪 Test it: shout, clap, whisper!',
        '🎉 Show off your noise detector!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Noise Detector',
      emoji: '🛠️',
      content: [
        'Build the program in 3 stages — have students test after each one.',
        'STAGE 1 — Display the volume: Use CyberPi\'s sound sensor to read "loudness". Clear the screen first, then print the volume value. Tip: the raw value fluctuates fast, so store it in a variable named "volume" to make it readable.',
        'STAGE 2 — Make a decision: Add a conditional that checks the volume against a threshold (the example uses 40, but students can choose their own). If the volume is above the threshold, broadcast an "alert" message.',
        'STAGE 3 — Define alert vs. standby: On "alert" → LEDs blink red AND the screen shows "Please be quiet". On standby (volume below threshold) → LEDs off and the warning text disappears.',
        'Once all three stages work together, the device continuously listens and reacts in real time.',
      ] as string[],
      studentContent: [
        '1️⃣ Read the volume and show it on screen (store it in a "volume" variable so it\'s steady)',
        '2️⃣ Add a rule: IF volume > 40 → send an "alert"',
        '3️⃣ On alert: 🔴 LEDs blink red + screen says "Please be quiet"',
        '4️⃣ When quiet again: LEDs off, message gone',
        '✅ Put it all together — your detector now reacts live!',
      ],
      images: [
        { src: '/lessons/mbot2-l1/program-full.png', kind: 'block', caption: 'The complete Noise Detector program in mBlock — build it stage by stage.' },
        { src: '/lessons/mbot2-l1/block-led-display.png', kind: 'block', caption: 'The "LED displays colour" block — pick the alert colour (red).' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Tune Your Detector',
      emoji: '🎚️',
      content: [
        'Change the threshold value and test it. What number works best for your classroom?',
        'Add a second level: a yellow "getting loud" warning before the red "too loud" alert.',
        'Make the alert friendlier or funnier — change the message or add a sound.',
      ] as string[],
      studentContent: [
        '🎚️ Change the loudness limit — what number is best?',
        '🟡 Add a "getting loud" yellow warning before red',
        '😄 Make your alert message fun!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Count how many times the room got "too loud" during the lesson and show the count on the screen.',
        'Use the joystick or buttons to let the user change the threshold without editing the code.',
        'Discuss: how could this become a real product for a library or hospital?',
      ] as string[],
      studentContent: [
        '🔢 Count how many times it got too loud and show the total',
        '🕹️ Use the buttons/joystick to change the limit live',
        '💡 How could this be a real product for a library?',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'The volume number on screen changes too fast to read',
          cause: 'The sound sensor updates continuously, so the raw value fluctuates every instant.',
          solution: 'Store the reading in a variable named "volume" and display the variable. Optionally add a short wait in the loop to slow updates.',
        },
        {
          problem: 'CyberPi won\'t connect to mBlock',
          cause: 'Device not added, wrong connection mode, or driver/Bluetooth issue.',
          solution: 'In mBlock, click "Add" and choose CyberPi, then Connect (USB or Bluetooth). Re-seat the USB cable, and make sure the CyberPi is powered on.',
        },
        {
          problem: 'Old text stays on the screen behind the new text',
          cause: 'The screen was not cleared before printing.',
          solution: 'Add the "clear screen" block at the start of the loop so each update shows cleanly. (Note: the standby step already clears it — don\'t clear twice.)',
        },
        {
          problem: 'LEDs stay red even when it\'s quiet — Suggested',
          cause: 'No standby branch, so the alert state is never reset.',
          solution: 'Make sure the ELSE / standby path turns the LEDs off and removes the warning text when volume is below the threshold.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student can give examples of different types of data.',
        'Student connected CyberPi and read the sound sensor.',
        'Student displayed the volume using a variable.',
        'Student used a threshold + conditional to trigger an alert.',
        'Student demonstrated the working detector and explained a real use.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Find 3 places in your home or neighbourhood where a noise detector would be useful. Write down what the "too loud" limit should be for each.',
        'List 3 other kinds of data you meet every day (e.g. a weather report, bus arrival times, a step counter) and what problem each one helps solve.',
        'Optional: sketch an upgrade for your detector and bring the idea next lesson.',
      ] as string[],
      studentContent: [
        '🏠 Find 3 places a noise detector would help — what\'s the right limit for each?',
        '📊 List 3 kinds of data you see every day and what they\'re for',
        '✏️ Sketch one upgrade idea for next time!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'BIG IDEA: The lesson is really about DATA — the noise detector is the hook. Keep linking "sensor reading" back to "this is data".',
        'THRESHOLD: 40 is just the example value. Encourage students to experiment — owning the number increases engagement.',
        'PACING: The 20-minute Elaborate build is the core. If short on time, trim the survey/discussion, not the build.',
        'DATA VARIABLE: The "store volume in a variable" trick is the key teaching moment — make sure everyone sees why the raw value is hard to read.',
        'REAL-WORLD TIE-IN: Libraries, hospitals, exam halls, cinemas are great discussion examples for where this matters.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l1-r1', title: 'Lesson 1 Visual Aids (Slides)',  type: 'slides', audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides referenced in the plan', needsReview: true },
    { id: 'mb2l1-r2', title: 'Demo Program (.mblock)',          type: 'code',   audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Finished noise detector program',        needsReview: true },
    { id: 'mb2l1-r3', title: 'Original Lesson Plan (PDF)',      type: 'pdf',    audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan',             needsReview: true },
  ],
};

// ─── Lesson 2: Voice Reactive Lights — Full Detail ───────────────
// Source: "Lesson 02_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_2: LessonDetail = {
  id: 'mbot2-l2',
  slug: 'voice-reactive-lights',
  title: 'Voice Reactive Lights',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 2,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Sound Sensor', 'LEDs & Colour', 'Bar Charts', 'Variables', 'Mind Mapping'],
  materials: [
    { item: 'Laptop/desktop with mBlock 5 installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                            quantity: '1 per student or pair' },
    { item: 'Speakers / music to play (Evaluate)',    quantity: '1 per classroom', isOptional: true },
    { item: 'Visual Aids slides (projector)',         quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Display a bar chart on the CyberPi screen.',
    'Change lighting effects and the bar chart based on the sound level.',
    'Use a mind map to analyse how to complete a project.',
    'Write a program that creates the Voice Reactive Lights project.',
  ],
  assessmentChecklist: [
    'Student detected the sound level using the sound sensor.',
    'Student changed LED colour and brightness based on volume.',
    'Student displayed sound levels as a bar chart on the screen.',
    'Student used variables to make multiple bars with different heights.',
    'Student presented their Voice Reactive Lights to the group.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Install mBlock 5 and confirm each laptop connects to a CyberPi in Upload mode.',
        'Open the Lesson 2 Visual Aids slides — they include musical-fountain pictures and a video used in Engage.',
        'Build the finished Voice Reactive Lights project yourself so you can demo it.',
        'Have music ready to play for the Evaluate showcase at the end.',
        'Prerequisite: students should already know CyberPi\'s main features and how to read its sensors (from Lesson 1).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–4: Show pictures/video comparing traditional fountains and musical fountains. Ask "Which do you like and why?" Then introduce how musical fountains work.',
          tip: 'Play a short musical-fountain video clip if you have one — it instantly sells the idea.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slide 6: Ask "How do the music, fountain, and lighting fit together?" Guide them to the rule: louder music → darker colour, higher spout, faster changes; softer music → lighter colour, lower spout, slower changes.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 8–9: Explain that although we can\'t build a real fountain, we can use CyberPi to make Voice Reactive Lights. Analyse the features together and draw a mind map (detect sound → set lights → draw bars).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 11–17: Connect the device and select Upload mode. Demonstrate reading the sound level, then build the program in two parts — lighting effects, then the volume bar chart. See the Main Activity below.',
          coachNote: 'Tip from the plan: have students add the "wait" block, then remove it, and compare — it shows why timing matters for smooth effects.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 19: Play music and invite students to present. Have them demo in small groups first, then ask volunteers to present to the whole class.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Make Lights Dance to Sound! 🎶',
      emoji: '🎯',
      studentTitle: 'Your Mission: Make Lights Dance to Sound! 🎶',
      content: [
        'Connect your CyberPi and switch to Upload mode.',
        'Read the sound level with the sound sensor.',
        'Make the LEDs change colour and brightness with the volume.',
        'Draw a bar chart on the screen that grows with the sound.',
        'Use variables to show four bars at different heights.',
        'Play music and watch your lights dance!',
      ] as string[],
      studentContent: [
        '🔌 Connect CyberPi (Upload mode)',
        '🎤 Read the sound level',
        '🌈 LEDs change colour + brightness with volume',
        '📊 Draw a bar chart that grows with the sound',
        '🔢 Use variables for 4 different bars',
        '🎶 Play music — watch them dance!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Build the Voice Reactive Lights',
      emoji: '🛠️',
      content: [
        'PART A — Lighting effects: Use the "set LED colour (RGB)" block (each colour 0–255; higher = brighter) and the "set brightness" block (0–100). Use "pick random () to ()" for the RGB values so colours change, and add a short "wait () seconds" between changes for a smooth transition. The lights start changing as soon as the program runs.',
        'PART B — Bar chart on screen: Use the "bar chart, add data" block to show the sound level. Set a different "brush colour" before each bar, otherwise all the data stacks into one bar.',
        'PART C — Different heights: To make bars of different heights, collect the volume into separate variables (Volume1–Volume4) at short intervals, then draw one coloured bar per variable.',
        'Run the lighting script and the bar-chart script from the SAME event block so they start together.',
      ] as string[],
      studentContent: [
        '🌈 PART A: LED colour with random RGB + a short wait for smooth changes',
        '📊 PART B: "bar chart, add data" with a different brush colour per bar',
        '🔢 PART C: store Volume1–4 in variables, then draw 4 coloured bars',
        '▶️ Start both scripts from the SAME event block so they run together!',
      ],
      images: [
        { src: '/lessons/mbot2-l2/blocks-bar-chart.png',   kind: 'block', caption: 'Set a brush colour before each "bar chart, add data" block — otherwise bars merge.' },
        { src: '/lessons/mbot2-l2/blocks-volume-vars.png', kind: 'block', caption: 'Collect the volume into Volume1–4 every 0.02s so each bar can differ.' },
        { src: '/lessons/mbot2-l2/program-bars-final.png', kind: 'block', caption: 'The finished script: four coloured bars driven by the four volume variables.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Make It Yours',
      emoji: '🎚️',
      content: [
        'Add the "wait" block, then remove it, and compare how the effect changes. Which feels better?',
        'Change the colour scheme so louder = darker (like the musical-fountain rule).',
        'Add more bars, or make the bars taller for louder sounds.',
      ] as string[],
      studentContent: [
        '⏱️ Try adding and removing the "wait" — which looks better?',
        '🎨 Make louder sounds = darker colours',
        '📈 Add more bars or make them taller!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Map the volume to spout "height" by changing how tall the tallest bar can grow.',
        'Add a "beat" feel: flash all LEDs white on the loudest peaks.',
        'Design a 30-second light show synced to a specific song.',
      ] as string[],
      studentContent: [
        '🌊 Make the tallest bar represent a fountain "spout"',
        '💥 Flash white on the loudest peaks',
        '🎵 Design a 30-second light show for a song!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'All the bars merge into one bar',
          cause: 'Every "bar chart, add data" used the same brush colour.',
          solution: 'Set a different brush colour before each bar. Same colour = the data is treated as one bar.',
        },
        {
          problem: 'The bars all have the same height',
          cause: 'The same value is used for each bar instead of separate readings.',
          solution: 'Store the volume into separate variables (Volume1–4) at short intervals, then draw each variable as its own bar.',
        },
        {
          problem: 'Lighting and bar chart are out of sync',
          cause: 'The two scripts start from different event blocks.',
          solution: 'Start both scripts from the same Event block so they run together.',
        },
        {
          problem: 'Light changes look jumpy — Suggested',
          cause: 'No transition time between colour changes.',
          solution: 'Add a short "wait () seconds" between changes; tune the value until the transition looks smooth.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student read the sound level with the sensor.',
        'Student changed LED colour/brightness from the volume.',
        'Student displayed sound as a bar chart.',
        'Student used variables for bars of different heights.',
        'Student presented their project.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Find a real place that uses lights + sound together (concert, fountain, game) and note how they connect.',
        'Sketch your dream light show: what colours happen at quiet vs. loud moments?',
        'Optional: plan which song you\'d sync your lights to next time.',
      ] as string[],
      studentContent: [
        '🔦 Find a real place that mixes lights + sound — how do they connect?',
        '🎨 Sketch your dream light show (quiet vs. loud)',
        '🎵 Pick a song to sync next time!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'BIG IDEA: This builds directly on Lesson 1 — the sound sensor again, but now driving richer output (colour + a live chart).',
        'KEY MISTAKE TO PRE-EMPT: same brush colour → merged bars. Show this on purpose, then fix it together.',
        'VARIABLES MOMENT: collecting Volume1–4 is the core concept — it\'s why bars can differ. Make sure everyone gets it.',
        'PACING: Lighting (Part A) is quick and rewarding; the bar chart (Parts B–C) is the harder part — leave most of the 20 min for it.',
        'SHOWCASE: the music + present finish is high-energy — protect the last 5 minutes for it.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l2-r1', title: 'Lesson 2 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (fountains, video)', needsReview: true },
    { id: 'mb2l2-r2', title: 'Demo Program (.mblock)',         type: 'code',   audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Finished Voice Reactive Lights program', needsReview: true },
    { id: 'mb2l2-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 3: Remote Classroom Polling — Full Detail ────────────
// Source: "Lesson 03_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_3: LessonDetail = {
  id: 'mbot2-l3',
  slug: 'remote-classroom-polling',
  title: 'Remote Classroom Polling',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['LAN / Wi-Fi', 'Broadcast & Receive', 'Variables', 'Bar Charts', 'Data Analysis'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed',     quantity: '1 per student or pair' },
    { item: 'CyberPi kit (≥2 boards to demo LAN)',       quantity: '2+ per classroom' },
    { item: 'Visual Aids slides (projector)',            quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Describe the features of a LAN, and broadcast and receive data over it.',
    'Generate a bar chart based on the votes.',
    'Analyse poll results and draw conclusions.',
    'Use a mind map to plan a remote classroom polling system.',
    'Write the programs that complete the polling project.',
  ],
  assessmentChecklist: [
    'Student can explain what a LAN is and how it differs from the Internet.',
    'Student broadcast and received a message over Wi-Fi/LAN between CyberPi boards.',
    'Student used a variable (VotingStatus) so each voter votes only once.',
    'Student counted votes with a conditional and displayed a bar chart.',
    'Student interpreted the result chart and drew a conclusion.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'You need at least TWO CyberPi boards to demonstrate LAN broadcasting (one initiator, one voter).',
        'In mBlock, you write two programs: select "CyberPi" (initiator) and "CyberPi 2" (voter) under Devices. Select Upload mode.',
        'Build and test both programs in advance — this is the most complex lesson in the module.',
        'Prepare a few fun poll questions (favourite song, movie star, game) for the live vote.',
        'Prerequisites: students can write block programs and know CyberPi\'s main features (Lessons 1–2).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–5: Ask about voting in competition shows — how does the live audience vote? Could people at home join? Introduce LAN: a closed, local network where only connected devices can share information (unlike the open Internet).',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 7–8: "We\'ll use CyberPi to form a LAN and run a poll — only this classroom can vote." Discuss the roles: an initiator starts the poll, the rest are voters, and when voting closes the initiator counts the votes.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 10–13: Demonstrate how the polling works and draw a mind map of the features (start poll → send options → cast votes → count → show results).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 15–26: Build TWO programs — initiator and voter — see the Main Activity. Use LAN "broadcast" / "when receiving … on Wi-Fi" blocks to communicate, a VotingStatus variable so each voter votes once, and a bar chart to show results.',
          coachNote: 'Edge case from the plan: if two boards send the same message on the LAN at the exact same instant, the receiver counts it once — but this is rare. Mention it only if asked.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 29: Run a real classroom poll (e.g. favourite song). When done, have students read the result chart and explain WHY the winner is popular.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Classroom Voting System! 🗳️',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Classroom Voting System! 🗳️',
      content: [
        'Learn what a LAN is — a private network just for this room.',
        'Program the INITIATOR board to start the poll and send the options.',
        'Program the VOTER board to show options and send a vote with the joystick.',
        'Make sure each voter can only vote once (use a VotingStatus variable).',
        'Count the votes on the initiator and show a bar chart.',
        'Run a real poll and read the results!',
      ] as string[],
      studentContent: [
        '📡 Learn what a LAN is (a private network for our room)',
        '▶️ INITIATOR: start the poll + send the options',
        '🕹️ VOTER: show options, vote with the joystick',
        '☝️ One vote each — use a VotingStatus variable',
        '📊 Count votes + show a bar chart',
        '🏆 Run a real poll and read the winner!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Build the Polling System (2 boards)',
      emoji: '🛠️',
      content: [
        'INITIATOR — start the poll: Create two variables for the option tallies and set both to 0. Broadcast "options" on Wi-Fi, show "Options sent. Poll starts", and set a timer for the voting period.',
        'VOTER — display options: "when receiving options broadcast on Wi-Fi" → clear screen and print the choices (e.g. Option A = joystick pulled ↑, Option B = pulled ↓).',
        'VOTER — cast a vote: Use a VotingStatus variable (0 = not voted). Repeat until voted: if the joystick is pulled, broadcast "vote" with the chosen value, show a confirmation, and set VotingStatus to 1 so they can\'t vote again.',
        'INITIATOR — count votes: "when receiving vote on Wi-Fi" during the voting period → check the received value and add 1 to the matching option\'s tally.',
        'INITIATOR — show results: When a button is pressed, display the tally as text and a bar chart (different colour per bar). Tip: add a base number to each tally so small results still look clear.',
      ] as string[],
      studentContent: [
        '▶️ INITIATOR: set both tallies to 0, broadcast "options", start a timer',
        '🕹️ VOTER: show options, then vote by pulling the joystick',
        '☝️ Use VotingStatus so you can only vote once',
        '🔢 INITIATOR: count each "vote" message into the right tally',
        '📊 Press a button to show the results as a bar chart!',
      ],
      images: [
        { src: '/lessons/mbot2-l3/voter-display-options.png',   kind: 'block', caption: 'VOTER: when "options" is received, show the choices on screen.' },
        { src: '/lessons/mbot2-l3/voter-cast-vote.png',         kind: 'block', caption: 'VOTER: pull the joystick to broadcast a "vote"; VotingStatus stops double-voting.' },
        { src: '/lessons/mbot2-l3/initiator-count-results.png', kind: 'block', caption: 'INITIATOR: on button press, tally the votes and draw a bar chart.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Complete the System',
      emoji: '🎚️',
      content: [
        'The example handles one option — extend it so BOTH options are sent, counted, and charted.',
        'Show both result bars in different colours at the same time.',
        'Add a clear "poll closed" message when the timer ends.',
      ] as string[],
      studentContent: [
        '➕ Make it work for BOTH options (not just one)',
        '🎨 Show both result bars in different colours',
        '⏰ Add a "poll closed!" message when time runs out',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a third option and a third joystick direction.',
        'Show live results that update as votes come in.',
        'Calculate and display the winning percentage, not just the count.',
      ] as string[],
      studentContent: [
        '3️⃣ Add a third option (and joystick direction)',
        '⚡ Show results updating live as votes arrive',
        '📈 Show the winning percentage, not just the count!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Voter board receives nothing',
          cause: 'The broadcast names don\'t match, or boards aren\'t on the same LAN.',
          solution: 'Make sure the "when receiving (…)" name is spelled exactly like the broadcast sent, and both boards joined the same Wi-Fi/LAN.',
        },
        {
          problem: 'A student can vote many times',
          cause: 'No VotingStatus check.',
          solution: 'Create a VotingStatus variable (0 = not voted). After a vote, set it to 1 and only allow voting while it is 0.',
        },
        {
          problem: 'Votes counted for the wrong option',
          cause: 'The conditional that checks the received value is missing or wrong.',
          solution: 'Check the broadcast value and add 1 to the matching tally. Build option A first, then duplicate the logic for option B.',
        },
        {
          problem: 'Bar chart is hard to read with few votes — Suggested',
          cause: 'Small numbers make tiny bars.',
          solution: 'Add a base number to each tally (e.g. value + 10) so the bars are clearly visible.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student explained what a LAN is.',
        'Student broadcast and received messages between boards.',
        'Student prevented double-voting with a variable.',
        'Student counted votes and drew a bar chart.',
        'Student interpreted the results.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'List 3 real systems that use voting or polling and how they collect the data.',
        'Write a poll question you\'d like to run in class and predict the result.',
        'Reflect: why might a closed LAN be safer than the open Internet for a classroom vote?',
      ] as string[],
      studentContent: [
        '🗳️ Find 3 real voting/polling systems — how do they collect data?',
        '❓ Write a poll question and predict the winner',
        '🔒 Why is a closed LAN safer than the open Internet for voting?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'HARDEST LESSON in the module — two programs on two boards. Build both yourself first.',
        'TEACH THE PATTERN: broadcast (send) ↔ when receiving (listen). Everything hinges on matching names.',
        'VotingStatus is the key concept — it\'s how we stop double votes. Spend time here.',
        'SCAFFOLD: the example does one option; completing the second is the main student challenge — pair students if needed.',
        'PAYOFF: the live class poll at the end is the motivator — leave time for it and make it fun.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l3-r1', title: 'Lesson 3 Visual Aids (Slides)',          type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (voting, LAN)', needsReview: true },
    { id: 'mb2l3-r2', title: 'Demo Programs — Initiator & Voter (.mblock)', type: 'code', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Both finished CyberPi programs', needsReview: true },
    { id: 'mb2l3-r3', title: 'Original Lesson Plan (PDF)',             type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 4: Houseplant Care — Full Detail ─────────────────────
// Source: "Lesson 04_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_4: LessonDetail = {
  id: 'mbot2-l4',
  slug: 'houseplant-care',
  title: 'Houseplant Care',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Light Sensor', 'Variables & Maths', 'Conditions & Alarms', 'Bar Charts', 'Simulation'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed',  quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                            quantity: '1 per student or pair' },
    { item: 'Example program file (3 plant sprites)', quantity: 'shared by coach' },
    { item: 'Visual Aids slides (projector)',         quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Explain the relationship between plants and water, and that different plants need different amounts.',
    'Simulate sunlight and monitor plant moisture with sensors.',
    'Send an alarm when water is insufficient or excessive.',
    'Use a mind map to analyse how a plant-monitoring device works.',
  ],
  assessmentChecklist: [
    'Student created a "light" variable from the light sensor.',
    'Student simulated water loss using moisture variables and division (different speeds per plant).',
    'Student displayed the three moisture levels as a bar chart (rounded to integers).',
    'Student sent an alarm when moisture went too low (<50) or too high (>110).',
    'Student used the joystick (choice variable) to select and water a plant.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'This project runs in mBlock LIVE mode (the stage drives the simulation) and uses an example program with three plant sprites — Cactus7, Pot plant12, Pot plant1.',
        'Have the example program ready to distribute, and open it yourself first.',
        'The three plants dry out at different speeds: Cactus (slow), Pot plant12 (medium), Pot plant1 (fast).',
        'Connect each CyberPi and switch mBlock to Live mode.',
        'Prerequisites: students can write block programs and know CyberPi\'s features (Lessons 1–3).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–7: Discuss why plants need water and that different plants need different amounts (cacti monthly, big-leaf plants daily, most plants weekly). Ask "What happens if we water too much or forget?" — both can kill a plant, and overwatering wastes water.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 9–11: Introduce the challenge — design a device that reminds plant lovers to water correctly. Ask what features it needs (detect a moisture problem; remind the user).',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 13–15: Show the desired outcome and have students draw a mind map of the device\'s functions (sense → simulate water loss → show moisture → alarm → water).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 17–33: Connect CyberPi in Live mode and open the example. Build the project in stages — simulate water loss, show moisture, raise alarms, and add joystick watering. See the Main Activity.',
          coachNote: 'Assume all three plants get the same sunlight. The DIFFERENT divisor per plant is what makes them dry at different speeds — that\'s the core maths idea.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 35: Students present their projects and give each other feedback. Ask each to introduce a real plant (name, features, care) — encourage quick online research.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Plant Carer! 🌱',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Plant Carer! 🌱',
      content: [
        'Use the light sensor to simulate sunlight drying the plants.',
        'Give each of the 3 plants its own moisture level that drops over time.',
        'Make thirsty plants dry faster and tough plants dry slower (using division).',
        'Show all 3 moisture levels as a bar chart.',
        'Sound an alarm if a plant is too dry or overwatered.',
        'Use the joystick to pick a plant and water it!',
      ] as string[],
      studentContent: [
        '☀️ Use the light sensor to simulate sunlight',
        '💧 Give each of 3 plants its own moisture level',
        '➗ Thirsty plants dry faster (smaller divisor!)',
        '📊 Show all 3 moisture levels as bars',
        '🚨 Alarm if too dry (<50) or overwatered (>110)',
        '🕹️ Joystick: pick a plant and water it!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Plant Monitor',
      emoji: '🛠️',
      content: [
        'SIMULATE WATER LOSS: Create a "light" variable from the light sensor. Give each plant a moisture variable (moisture1–3) starting at 100. In a forever loop, while moisture > 0, subtract light ÷ divisor. Use a DIFFERENT divisor per plant — Cactus7 = 30 (slow), Pot plant12 = 20 (medium), Pot plant1 = 10 (fast). Add a "wait" so it doesn\'t drop too quickly, and keep moisture above 0.',
        'SHOW MOISTURE: Draw a bar chart of the three moisture levels, a different brush colour per plant. Use "round" because CyberPi only displays integers.',
        'RAISE ALARMS: If moisture < 50 the plant lacks water; if moisture > 110 it\'s overwatered. When either is true, light up an indicator. When moisture returns to normal, turn the alarm off. (Students can tune these numbers.)',
        'WATER WITH THE JOYSTICK: Create a "choice" variable limited to 1–3 to pick a plant (an arrow sprite shows which). Pull the joystick down to water the selected plant (increase its moisture).',
      ] as string[],
      studentContent: [
        '➗ Each plant loses water = light ÷ its divisor (30 / 20 / 10)',
        '📊 Show the 3 moisture levels as a rounded bar chart',
        '🚨 Alarm when moisture < 50 (dry) or > 110 (overwatered)',
        '🕹️ "choice" (1–3) picks a plant; pull down to water it',
      ],
      images: [
        { src: '/lessons/mbot2-l4/script-water-loss.png',     kind: 'block', caption: 'Water loss: subtract light ÷ divisor each second (smaller divisor = dries faster).' },
        { src: '/lessons/mbot2-l4/script-moisture-chart.png', kind: 'block', caption: 'Show all three moisture levels as a coloured bar chart (rounded to integers).' },
        { src: '/lessons/mbot2-l4/script-select-plant.png',   kind: 'block', caption: 'Use "choice" (1–3) to select a plant; an arrow glides under it.' },
        { src: '/lessons/mbot2-l4/script-water-plant.png',     kind: 'block', caption: 'Pull the joystick down to water the selected plant (raise its moisture).' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Complete All Three Plants',
      emoji: '🎚️',
      content: [
        'The examples often show one plant — complete the water-loss, alarm, and indicator scripts for all three.',
        'Tune the divisors and alarm thresholds so each plant behaves realistically.',
        'Add a "healthy" green indicator when moisture is in the good range.',
      ] as string[],
      studentContent: [
        '🌵 Finish the scripts for ALL three plants',
        '🎚️ Tune each plant\'s speed and alarm limits',
        '✅ Add a green "healthy" light for the good range',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a real soil-moisture sensor instead of the simulation, if you have one.',
        'Log how many times each plant needed watering during the lesson.',
        'Research a real plant and set its divisor/thresholds to match its true water needs.',
      ] as string[],
      studentContent: [
        '🌡️ Use a real moisture sensor instead of the simulation',
        '🔢 Count how many times each plant needed water',
        '🔎 Research a real plant and match its water needs!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Moisture drops to a negative number',
          cause: 'No lower-bound check on the variable.',
          solution: 'Only subtract while "moisture > 0" so it can\'t go negative.',
        },
        {
          problem: 'All three plants dry at the same speed',
          cause: 'The same divisor was used for each plant.',
          solution: 'Use different divisors: Cactus7 = 30 (slow), Pot plant12 = 20, Pot plant1 = 10 (fast).',
        },
        {
          problem: 'Moisture drops far too fast',
          cause: 'No wait in the loop.',
          solution: 'Add a "wait () seconds" block in the loop to slow the simulation.',
        },
        {
          problem: 'Bar chart shows odd long decimals',
          cause: 'CyberPi can only display integers.',
          solution: 'Wrap the moisture value in a "round" block before charting.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student simulated water loss with a light variable and division.',
        'Student gave each plant a different drying speed.',
        'Student displayed rounded moisture as a bar chart.',
        'Student raised alarms for too-dry / overwatered.',
        'Student watered a selected plant with the joystick.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Pick a real houseplant and find out how often it should be watered — what divisor would model it?',
        'Explain in your own words why overwatering can be as harmful as underwatering.',
        'Sketch a real product version of this device — where would the sensor go?',
      ] as string[],
      studentContent: [
        '🪴 Pick a real plant — how often does it need water?',
        '💭 Why is overwatering as bad as underwatering?',
        '✏️ Sketch a real version — where does the sensor go?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'CORE MATHS IDEA: dividing the light value by a different number per plant models different drought-resistance. This is the concept to land.',
        'LIVE MODE: this project runs on the stage (sprites) in Live mode, not Upload — a good contrast with earlier lessons.',
        'SCAFFOLD: students complete the second and third plants by copying the first plant\'s pattern. Pair them if needed.',
        'GUARDRAILS: the "moisture > 0" check and the "wait" block both prevent runaway values — make sure both are in place.',
        'CROSS-CURRICULAR: great link to science (transpiration, photosynthesis) — lean into it during Engage.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l4-r1', title: 'Lesson 4 Visual Aids (Slides)',  type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (plants, care)', needsReview: true },
    { id: 'mb2l4-r2', title: 'Example Program — 3 Plants (.mblock)', type: 'code', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Starter program with the three plant sprites', needsReview: true },
    { id: 'mb2l4-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 5: Smart Notifier — Full Detail ──────────────────────
// Source: "Lesson 05_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_5: LessonDetail = {
  id: 'mbot2-l5',
  slug: 'smart-notifier',
  title: 'Smart Notifier',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m2',
  moduleTitle: 'Module 2: Smart Devices',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Light Sensor', 'Shake Detection', 'Timer', 'Modes & Buttons', 'Healthy Habits'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                           quantity: '1 per student or pair' },
    { item: 'Visual Aids slides (projector)',        quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Use CyberPi to measure light intensity and shaking status.',
    'Define notifications for specific scenarios based on needs.',
    'Use a mind map to analyse how to create a smart notifier.',
    'Program a Smart Notifier with multiple functions and modes.',
  ],
  assessmentChecklist: [
    'Student measured light intensity and detected shaking.',
    'Student built a startup screen to choose a mode (button A / B).',
    'Student programmed Reading Mode with auto-brightness (LED = 100 − ambient light).',
    'Student programmed Sitting Mode that alerts after sitting too long (timer).',
    'Student reset the timer when shaking (movement) is detected.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Connect a CyberPi and switch mBlock to Live mode.',
        'Build both modes yourself: Reading Mode (auto-brightness) and Sitting Mode (sit-too-long alert).',
        'Key blocks: light sensor, "shaken detected?", timer, reset timer, buttons A/B, LED, sound.',
        'Have the mind-map slide ready for the Explain phase.',
        'Prerequisites: students can use sensors and CyberPi (Lessons 1–4).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–7: Discuss daily habits that harm health (slouching, using phones lying down, staying up late). Note how technology already tracks health (step counters, heart-rate, sleep). Frame the project: use CyberPi to help build healthy habits.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 9–12: Discuss home scenarios — sitting too long, reading in poor light. Ask "How could a device help?" Lead to: a device that monitors conditions and gives alerts (stand up; turn on lights).',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 14–17: Introduce the two-mode design — Reading Mode and Sitting Mode — selectable by the user. Draw a mind map of the required features.',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 19–28: In Live mode, build a startup screen to pick a mode, then Reading Mode (auto-brightness) and Sitting Mode (sit-too-long alert using the timer + shake detection). See the Main Activity.',
          coachNote: 'Key trick: when one mode is selected, "stop other scripts in sprite" so the two modes don\'t run at once.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 30–31: 2–3 students present their notifier and explain what\'s special. Discuss other unhealthy habits and how tech could help.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Health Helper! 🧘',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Health Helper! 🧘',
      content: [
        'Make a startup screen: press A for Reading Mode, B for Sitting Mode.',
        'Reading Mode: auto-adjust the LED brightness to the room light.',
        'Sitting Mode: start a timer and alert if you sit too long.',
        'Reset the timer whenever movement (shaking) is detected.',
        'Add a colour, sound, or message for each alert.',
        'Show it off and explain how it keeps people healthy!',
      ] as string[],
      studentContent: [
        '🅰️🅱️ Startup: A = Reading Mode, B = Sitting Mode',
        '📖 Reading Mode: LED brightness = 100 − room light',
        '⏱️ Sitting Mode: alert if the timer gets too high',
        '🤸 Reset the timer when you move (shake detected)',
        '🚨 Add colour / sound / message to alerts',
        '🎤 Present it — how does it keep people healthy?',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Two Modes',
      emoji: '🛠️',
      content: [
        'STARTUP: Show a screen prompting the user to pick a mode with buttons A or B.',
        'READING MODE (button A): Stop the other mode\'s scripts, clear the screen, and print reading advice. Add AUTO-BRIGHTNESS: set the LED brightness to "100 − ambient light", so darker rooms → brighter LEDs and bright rooms → dimmer LEDs.',
        'SITTING MODE (button B): Stop the other scripts, reset the timer, and print a posture reminder. Then forever: if the timer goes above ~10 seconds, alert (red LEDs, "You\'ve sat too long. Stand up.", a sound).',
        'MOVEMENT RESET: if "shaken detected?", reset the timer, turn off the alert, and show "Improve your sitting posture." — so moving counts as a break.',
      ] as string[],
      studentContent: [
        '🅰️ Reading Mode: print advice + LED brightness = 100 − room light',
        '🅱️ Sitting Mode: if timer > 10 → red LEDs + "stand up" + sound',
        '🤸 If shaken → reset timer + clear the alert',
        '🛑 Use "stop other scripts" so only one mode runs at a time!',
      ],
      images: [
        { src: '/lessons/mbot2-l5/reading-mode.png',       kind: 'block', caption: 'Reading Mode (button A): stop other scripts, then show reading advice.' },
        { src: '/lessons/mbot2-l5/sitting-mode-alert.png', kind: 'block', caption: 'Sitting Mode (button B): alert when the timer passes the limit.' },
        { src: '/lessons/mbot2-l5/sitting-mode-shake.png', kind: 'block', caption: 'Movement detected → reset the timer and clear the alert.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Make It Smarter',
      emoji: '🎚️',
      content: [
        'Tune the "too long" time and the brightness formula for your room.',
        'Add a gentle warning before the full alert (e.g. yellow at 8s, red at 12s).',
        'Add a third mode of your own (posture, water-break, screen-time…).',
      ] as string[],
      studentContent: [
        '🎚️ Tune the "too long" time and brightness for your room',
        '🟡 Add a gentle warning before the big alert',
        '➕ Invent a third mode (water break? screen time?)',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Count how many alerts happened and show a daily total.',
        'Make the alert escalate if it\'s ignored (louder / brighter over time).',
        'Design the icons/screens so a non-reader could use it.',
      ] as string[],
      studentContent: [
        '🔢 Count the alerts and show a daily total',
        '📢 Make the alert escalate if ignored',
        '🎨 Design icons so anyone could use it!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Both modes seem to run at once',
          cause: 'The other mode\'s scripts were not stopped when a mode was chosen.',
          solution: 'At the start of each mode, use "stop other scripts in sprite" so only one runs.',
        },
        {
          problem: 'LED brightness goes the wrong way',
          cause: 'Brightness set directly to the light value instead of the inverse.',
          solution: 'Use "100 − ambient light" so darker rooms give brighter LEDs.',
        },
        {
          problem: 'Alert never triggers',
          cause: 'Timer never reaches the threshold, or it resets every loop.',
          solution: 'Only reset the timer on movement (shaken). Check the threshold value.',
        },
        {
          problem: 'Alert never stops — Suggested',
          cause: 'No reset path when the person moves.',
          solution: 'Add the "if shaken" branch that resets the timer and clears the alert.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student measured light and detected shaking.',
        'Student built a mode-selection startup.',
        'Student implemented auto-brightness in Reading Mode.',
        'Student implemented the sit-too-long alert in Sitting Mode.',
        'Student reset the alert on movement.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'List 3 of your own habits a Smart Notifier could help with.',
        'For one habit, decide the sensor and the alert you\'d use.',
        'Research one real wearable and what it measures.',
      ] as string[],
      studentContent: [
        '📝 List 3 habits a Smart Notifier could help you with',
        '🔧 Pick one — which sensor and which alert?',
        '⌚ Research a real wearable — what does it measure?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'THEME: healthy habits + AI/sensors — a strong real-world hook, especially post-pandemic framing in the slides.',
        'KEY PATTERN: "modes" via buttons + "stop other scripts" — a reusable structure students will use again.',
        'AUTO-BRIGHTNESS: the "100 − light" inverse is a neat, intuitive maths idea — demo it live by covering the sensor.',
        'TIMER + SHAKE: the timer measures inactivity; shaking resets it. Make that relationship explicit.',
        'KEEP IT PERSONAL: let students pick habits they actually care about — engagement soars.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l5-r1', title: 'Lesson 5 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (health, modes)', needsReview: true },
    { id: 'mb2l5-r2', title: 'Demo Program (.mblock)',         type: 'code',   audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Finished Smart Notifier program', needsReview: true },
    { id: 'mb2l5-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 6: Parcel Locker — Full Detail ───────────────────────
// Source: "Lesson 06_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_6: LessonDetail = {
  id: 'mbot2-l6',
  slug: 'parcel-locker',
  title: 'Parcel Locker',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m2',
  moduleTitle: 'Module 2: Smart Devices',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Variables', 'Random Numbers', 'Verification Logic', 'Input & Answer', 'Timers'],
  materials: [
    { item: 'Laptop/desktop with mBlock 5 installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                             quantity: '1 per student or pair' },
    { item: 'Preset program file (locker sprite)',     quantity: 'shared by coach' },
    { item: 'Visual Aids slides (projector)',          quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'List ways to receive parcels and describe the value of parcel lockers.',
    'Explain how a parcel locker works; program sending and collecting with a pickup code.',
    'Use a mind map to analyse the features of a parcel locker.',
    'Apply variables to complete a parcel-locker system.',
  ],
  assessmentChecklist: [
    'Student stored a generated pickup code in a "PickupCode" variable.',
    'Student generated a 4-digit (pseudo-random) pickup code.',
    'Student sent reminders if the parcel was uncollected (24h / 48h, simulated with seconds).',
    'Student asked for input and compared the answer to the stored code.',
    'Student opened the door only when the entered code was correct.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Connect CyberPi to mBlock and open the preset program (it includes the parcel-locker sprite).',
        'Build the system yourself: generate code → notify → verify on input → open door.',
        'Note the time-saver: use 24 SECONDS to represent 24 HOURS for the reminders.',
        'Key concepts: variables, pseudo-random numbers, "ask … and wait" + "answer", comparison.',
        'Prerequisites: block coding + how to use variables (Lessons 1–5).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–5: Ask how students receive parcels (home, store, locker). Discuss: if nobody\'s home, a locker is safest — only the recipient with a one-off code can open it, and it works 24/7.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 7–9: How does the recipient know the parcel arrived? A text with a pickup code → go to the locker → enter the code → the correct code pops the door open.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 11–13: Demonstrate the locker and draw a mind map of its features (generate code → notify → remind → verify → open/close).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 15–23: Open the preset file. Build: generate & store the code, notify the recipient, send 24h/48h reminders, then verify the entered code and open the door. See the Main Activity.',
          coachNote: 'Use 24 seconds = 24 hours so reminders are testable in class.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 25–26: Students present. Ask "How is DATA used here?" — both the generated code and the entered code are data used to verify identity.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Parcel Locker! 📦',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Parcel Locker! 📦',
      content: [
        'Generate a random 4-digit pickup code and store it in a variable.',
        'Show the code on CyberPi like a text message to the recipient.',
        'Send a reminder if the parcel isn\'t collected (24h, then 48h).',
        'Ask the user to enter the code when they tap "Pick Up".',
        'If the code matches → open the door. If not → "try again".',
        'Close the door after the parcel is taken.',
      ] as string[],
      studentContent: [
        '🔢 Make a random 4-digit code → store in PickupCode',
        '📱 Show the code like a text message',
        '⏰ Remind after 24h, then 48h (use seconds!)',
        '⌨️ Tap "Pick Up" → ask for the code',
        '✅ Correct → door opens · ❌ wrong → try again',
        '🚪 Close the door after taking the parcel',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Locker',
      emoji: '🛠️',
      content: [
        'GENERATE & NOTIFY: Make a "PickupCode" variable and set it to a pseudo-random number (4 digits = 1000–9999; for 5 digits use 10,000–99,999). Display it on CyberPi like a delivery notification.',
        'REMINDERS: If the parcel isn\'t collected, send a reminder after 24h and again after 48h. To test in class, use 24 seconds to stand in for 24 hours.',
        'COLLECT (verify): When the user taps "Pick Up", use "ask … and wait" to get input and compare "answer = PickupCode". If correct, broadcast "Parcel taken out", open the door, and say "Close the door after you take your parcel." If wrong, say "Pickup code incorrect. Try again."',
        'CLOSE: After the parcel is removed, clicking the door closes it.',
      ] as string[],
      studentContent: [
        '🔢 PickupCode = random 1000–9999, then show it',
        '⏰ Reminder after 24s and 48s (= 24h/48h)',
        '⌨️ Ask for the code → if answer = PickupCode → open!',
        '🚪 Wrong code → "try again"; after pickup → close door',
      ],
      images: [
        { src: '/lessons/mbot2-l6/pickup-reminders.png', kind: 'block', caption: 'Reminders: after 24s and 48s (standing in for 24h/48h), re-send the pickup code.' },
        { src: '/lessons/mbot2-l6/verify-code.png',      kind: 'block', caption: 'Verify on pickup: if the entered answer equals PickupCode, open the door.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Make It Robust',
      emoji: '🎚️',
      content: [
        'Limit the number of wrong attempts before locking for a while.',
        'Generate a fresh code for every new parcel.',
        'Show a friendly confirmation screen when the door opens.',
      ] as string[],
      studentContent: [
        '🔒 Lock after too many wrong tries',
        '🔁 New code for every new parcel',
        '🎉 Friendly "door open!" confirmation',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Support multiple lockers, each with its own code.',
        'Log how long the parcel waited before pickup.',
        'Add a "resend code" button for the recipient.',
      ] as string[],
      studentContent: [
        '🗄️ Support multiple lockers with different codes',
        '⏱️ Log how long the parcel waited',
        '🔁 Add a "resend my code" button!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Correct code is rejected',
          cause: 'Comparing different types, or the code changed after being shown.',
          solution: 'Store the code in PickupCode once, then compare "answer = PickupCode". Don\'t regenerate it before verifying.',
        },
        {
          problem: 'Code isn\'t 4 digits',
          cause: 'Random range is wrong.',
          solution: 'Use 1000–9999 for 4 digits (or 10000–99999 for 5).',
        },
        {
          problem: 'Reminders never appear in class',
          cause: 'Using real 24-hour waits.',
          solution: 'Use 24 seconds to represent 24 hours during testing.',
        },
        {
          problem: 'Door won\'t close — Suggested',
          cause: 'No close handler on the door sprite.',
          solution: 'Add "when this sprite clicked → close" logic to the door after pickup.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student generated and stored a pickup code.',
        'Student displayed it like a notification.',
        'Student sent 24h/48h reminders (simulated).',
        'Student verified entered input against the code.',
        'Student opened the door only on a correct code.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Where else are one-time codes used (banking, login, tickets)? List 3.',
        'Why is a one-off code safer than a fixed password for a locker?',
        'Sketch how your locker would tell the courier which box is free.',
      ] as string[],
      studentContent: [
        '🔐 Where else are one-time codes used? List 3',
        '🤔 Why is a one-off code safer than a fixed password?',
        '✏️ How would the locker show the courier a free box?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'CORE CONCEPT: a variable storing a code + a comparison = verification. This is the same idea behind passwords and OTPs.',
        'RANDOM RANGE: tie digit-count to the range (1000–9999) — a nice maths connection.',
        'TIME COMPRESSION: 24s = 24h is a useful simulation habit students will reuse.',
        'DATA FRAMING: the Evaluate question ("how is data used?") ties back to the whole module\'s data theme.',
        'PRESET FILE: starts students from the locker sprite so the 20 minutes focus on logic, not setup.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l6-r1', title: 'Lesson 6 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (parcel lockers)', needsReview: true },
    { id: 'mb2l6-r2', title: 'Preset Program (.mblock)',       type: 'code',   audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Starter file with locker sprite', needsReview: true },
    { id: 'mb2l6-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 7: Intelligent Vehicles — Full Detail ────────────────
// Source: "Lesson 07_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_7: LessonDetail = {
  id: 'mbot2-l7',
  slug: 'intelligent-vehicles',
  title: 'Intelligent Vehicles',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m2',
  moduleTitle: 'Module 2: Smart Devices',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 4,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Speech Recognition', 'Functions', 'Colour Sensing', 'Conditionals', 'Autonomy'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed',  quantity: '1 per student or pair' },
    { item: 'CyberPi kit + microphone access',        quantity: '1 per student or pair' },
    { item: 'Cognitive Services extension (mBlock)',  quantity: 'enabled in mBlock' },
    { item: 'Visual Aids slides (projector)',         quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Identify the roles and importance of data in intelligent vehicles.',
    'Describe how autonomous lane-keeping and internet navigation work.',
    'Use a mind map to plan an intelligent-vehicle project.',
    'Use functions to simulate lane keeping and a voice navigation system.',
  ],
  assessmentChecklist: [
    'Student added the Cognitive Services extension and used speech recognition.',
    'Student created a reusable "drive" function for lane keeping.',
    'Student used colour-sensing to keep the vehicle in its lane and turn at corners.',
    'Student navigated to a spoken destination (e.g. hospital / grocery).',
    'Student stopped the vehicle based on "distance to" the destination.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'In mBlock, add the "Cognitive Services" extension (this provides the speech-recognition block) and check the microphone works.',
        'Open the preset stage with the vehicle, lanes, and destination sprites (map pin, hospital, grocery).',
        'Build it yourself: speak a destination → map pin appears → vehicle auto-drives (lane keeping) → stops at the destination.',
        'Note the vehicle/lane colours: vehicle = green, lane = dark grey; left sensor = light blue, right sensor = dark blue.',
        'Prerequisites: block coding + CyberPi features (Lessons 1–6). This is the hardest lesson in the module — functions + colour logic.',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–7: Introduce intelligent vehicles vs. conventional cars — internet navigation, autonomous driving, and human intervention. Pose the keep-in-mind question: "How do lane keeping and navigation use DATA?" Have students write it down.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 9–11: Show the project — say a destination, the car plans a route and drives there itself. Group the features into lane keeping and positioning.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 13–14: Draw a mind map of the functions (listen → mark destination → drive in lane → stop at destination).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 16–33: Add Cognitive Services for speech. Build: recognise the spoken destination, animate a map pin (a "show up" function), a "drive" function for lane keeping (colour sensing + corner turns), and stop using "distance to". See the Main Activity.',
          coachNote: 'Two FUNCTIONS here ("show up", "drive") — this is the lesson where reusable functions really pay off.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 35–37: Students demo. Return to the big question: how do lane keeping and navigation use data? (Colours, sensor touches, distance, and the spoken command are all data the car acts on.)',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Self-Driving Car! 🚗',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Self-Driving Car! 🚗',
      content: [
        'Turn on speech recognition so the car listens for a destination.',
        'Make a map pin bounce up at the place you said.',
        'Build a "drive" function that keeps the car in its lane.',
        'Use colours: if a side sensor leaves the lane, turn the other way.',
        'Drive until the car is close to the destination, then stop.',
        'Try different destinations — hospital, grocery, school!',
      ] as string[],
      studentContent: [
        '🎙️ Speech recognition: the car listens for a place',
        '📍 A map pin bounces up where you said',
        '🛣️ "drive" function keeps the car in its lane',
        '↪️ Side sensor leaves the lane → turn the other way',
        '🛑 Stop when close to the destination (distance < 55)',
        '🏥🛒 Try hospital, grocery, school!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Intelligent Vehicle',
      emoji: '🛠️',
      content: [
        'LISTEN: Add Cognitive Services and use the speech-recognition block (triggered by, e.g., pressing space). Store the recognised destination.',
        'MARK DESTINATION: Hide the map pin at first. Create a "show up" function with a bouncing animation. When a destination is recognised, send it to the map pin and call "show up" at the right place (hospital, grocery…).',
        'DRIVE (lane keeping) — create a "drive" function: if the green car is touching the dark-grey lane, move forward. If the LEFT sensor (light blue) leaves the lane, turn right; if the RIGHT sensor (dark blue) leaves the lane, turn left. Reuse this function to stay on the road.',
        'STOP AT DESTINATION: If the speech result contains "hospital", broadcast Hospital and repeat "drive" until "distance to Hospital" < 55, then stop. Do the same for grocery and other places (55 is just a reference — tune it).',
      ] as string[],
      studentContent: [
        '🎙️ Recognise the spoken destination',
        '📍 "show up" function: bounce the map pin at the place',
        '🛣️ "drive" function: green touches grey → move; side sensor off-lane → turn',
        '🛑 If heard "hospital" → drive until distance < 55, then stop',
      ],
      images: [
        { src: '/lessons/mbot2-l7/function-drive.png',     kind: 'block', caption: 'The "drive" function: stay in lane (green on grey) and turn when a side sensor leaves the lane.' },
        { src: '/lessons/mbot2-l7/navigate-hospital.png',  kind: 'block', caption: 'Heard "hospital" → drive until distance to Hospital < 55, then stop.' },
        { src: '/lessons/mbot2-l7/navigate-grocery.png',   kind: 'block', caption: 'Same pattern for "grocery" — reusing the drive function.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Add Destinations',
      emoji: '🎚️',
      content: [
        'Add more destinations (school, tower, home) with their own map-pin positions.',
        'Tune the stop "distance" so the car parks neatly at each place.',
        'Improve cornering so the car turns smoothly, not jerkily.',
      ] as string[],
      studentContent: [
        '🏫 Add school, tower, home destinations',
        '🅿️ Tune the stop distance so it parks neatly',
        '↩️ Make the turns smoother!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a spoken "stop" command for human intervention.',
        'Show the planned route or current speed on screen.',
        'Handle an unknown destination gracefully ("Sorry, I don\'t know that place").',
      ] as string[],
      studentContent: [
        '🗣️ Add a spoken "stop" command',
        '🗺️ Show the route or speed on screen',
        '🤷 Handle places it doesn\'t know nicely',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Speech block is missing',
          cause: 'Cognitive Services extension not added.',
          solution: 'In mBlock, open Extensions and add "Cognitive Services", then the speech-recognition block appears.',
        },
        {
          problem: 'Car drifts off the road',
          cause: 'Wrong colour values in the sensing blocks.',
          solution: 'Use the colour picker to set the exact car (green), lane (dark grey), and sensor colours. Left off-lane → turn right; right off-lane → turn left.',
        },
        {
          problem: 'Car never stops at the destination',
          cause: 'Distance threshold too small, or wrong destination sprite.',
          solution: 'Use "repeat until distance to (place) < 55" and tune 55. Make sure the broadcast/place names match.',
        },
        {
          problem: 'Map pin hidden behind buildings — Suggested',
          cause: 'Layer order.',
          solution: 'Use "go to front layer" so the pin sits on top, and hide it until a destination is received.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student used speech recognition for the destination.',
        'Student created and reused a "drive" function.',
        'Student kept the car in lane with colour sensing.',
        'Student navigated to a spoken destination.',
        'Student stopped using a distance check.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Answer the big question in writing: how do lane keeping and navigation use data?',
        'List 3 kinds of data a real self-driving car senses.',
        'Why are functions ("drive", "show up") useful in a big program?',
      ] as string[],
      studentContent: [
        '📝 How do lane keeping & navigation use data?',
        '🚗 List 3 kinds of data a real self-driving car senses',
        '🧩 Why are functions useful in a big program?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'HARDEST LESSON in the module: speech recognition + two functions + colour logic. Build it fully beforehand.',
        'FUNCTIONS are the star here — "drive" and "show up" show why we package reusable code. Emphasise this.',
        'COLOUR PICKER precision matters — most "car drives off road" issues are wrong colours.',
        'DATA THEME PAYOFF: the opening question gets answered at the end — colours, distances, and speech are all data.',
        'TIME: 20 min is tight for this much — pre-load the stage/sprites so students code logic, not setup.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l7-r1', title: 'Lesson 7 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (intelligent vehicles)', needsReview: true },
    { id: 'mb2l7-r2', title: 'Preset Program (.mblock)',       type: 'code',   audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Stage with vehicle, lanes, destinations', needsReview: true },
    { id: 'mb2l7-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 8: Bus Tracker — Full Detail ─────────────────────────
// Source: "Lesson 08_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_8: LessonDetail = {
  id: 'mbot2-l8',
  slug: 'bus-tracker',
  title: 'Bus Tracker',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m2',
  moduleTitle: 'Module 2: Smart Devices',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Variables', 'Real-time Data', 'Maths & Estimation', 'Broadcast', 'Conditionals'],
  materials: [
    { item: 'Desktop/laptop with mBlock installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                           quantity: '1 per student or pair' },
    { item: 'Demo program (circle bus line)',        quantity: 'shared by coach' },
    { item: 'Visual Aids slides (projector)',        quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Explain how a bus tracker works.',
    'Gather real-time bus information and calculate the expected arrival time.',
    'Use a mind map to plan a bus tracker.',
    'Program a working bus-tracker project.',
  ],
  assessmentChecklist: [
    'Student created a "boarding stop" variable and selected a stop with buttons A/B.',
    'Student compared boarding stop vs. bus location (coming / left / arrived).',
    'Student calculated stops-away correctly around the looped line.',
    'Student estimated arrival time (stops away × 3 minutes).',
    'Student sent an arrival notification when the bus reached the stop.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Open the demo program: clicking the green flag sends the bus clockwise around an 8-stop circle line. Connect CyberPi and use Live mode.',
        'Know the line: Stop 1 = Tiny Park, Stop 3 = Home, Stop 7 = Maker School (the preset "home"=3, "school"=7).',
        'Build the tracker yourself: pick a stop → compute stops-away → estimate time → notify on arrival.',
        'The bus sprite has custom blocks "1-2", "2-3" etc.; add a broadcast "real-time bus location" after each so the tracker updates.',
        'Prerequisites: students can display text, play sounds, and light LEDs on CyberPi (Lessons 1–7).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–4: "Ever waited ages for a bus, or just missed one?" Discuss real-time bus info and the Intelligent Bus System — locations, passenger counts, traffic — and the role of data.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 6–7: "You commute by bus daily — what info matters most?" Surface: real-time location, arrival time, and a heads-up notification when the bus is near.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 9–12: Demonstrate the tracker and draw a mind map of its features (pick stop → track bus → estimate time → notify).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 14–25: Open the demo. Build: choose a boarding stop (buttons A/B), receive the bus location, compute stops-away around the loop, estimate arrival (×3 min), and notify on arrival. See the Main Activity.',
          coachNote: 'Add a broadcast "real-time bus location" after each bus custom block so the tracker recalculates every time the bus moves a stop.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 27–28: Students present. Discuss "How could you improve the local bus system?"',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Bus Tracker! 🚌',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Bus Tracker! 🚌',
      content: [
        'Pick your boarding stop with a button (Home or School).',
        'Get the bus\'s current location on the loop.',
        'Work out how many stops away the bus is.',
        'Estimate the arrival time (3 minutes per stop).',
        'Show a notification when the bus arrives at your stop.',
        'Watch the info update as the bus moves!',
      ] as string[],
      studentContent: [
        '🅰️🅱️ Pick your stop (Home or School)',
        '📍 Get the bus\'s current location',
        '🔢 How many stops away is it?',
        '⏱️ Estimate time = stops away × 3 min',
        '🔔 Notify when the bus arrives!',
        '🔄 Info updates as the bus moves',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Bus Tracker',
      emoji: '🛠️',
      content: [
        'CHOOSE A STOP: Create a "boarding stop" variable set to 0 at startup. Button A sets it to home (3); button B sets it to school (7).',
        'TRACK THE BUS: A "bus location" variable holds the bus\'s current stop (1–8). On "when I receive real-time bus location", compare: boarding stop > bus location = still coming; boarding stop < bus location = already left (wrap around the loop); equal = arrived.',
        'STOPS AWAY (looped maths): If boarding stop > bus location, stops away = boarding stop − bus location. If boarding stop < bus location (bus passed it), it wraps: 8 − bus location + boarding stop.',
        'ESTIMATE TIME: It takes 3 minutes between stops, so arrival time = stops away × 3. Display it.',
        'ARRIVE: When bus location = boarding stop, play a sound, show "Bus arrives!", flash the LEDs, and reset boarding stop to 0.',
      ] as string[],
      studentContent: [
        '🅰️🅱️ boarding stop: A = Home (3), B = School (7)',
        '🔢 stops away = boarding − bus location (or 8 − bus + boarding if it passed)',
        '⏱️ arrival time = stops away × 3 minutes',
        '🔔 bus location = boarding stop → "Bus arrives!" + sound + LEDs',
      ],
      images: [
        { src: '/lessons/mbot2-l8/route-map.png',     kind: 'photo', caption: 'The 8-stop circle line: the bus travels clockwise from Tiny Park (Stop 1).' },
        { src: '/lessons/mbot2-l8/distance-calc.png', kind: 'block', caption: 'Stops-away: a normal subtraction, or wrap around the loop (8 − bus + boarding) once the bus has passed.' },
        { src: '/lessons/mbot2-l8/arrival-alert.png', kind: 'block', caption: 'On arrival (bus location = boarding stop): sound, "Bus arrives!", LEDs, then reset.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Make It Useful',
      emoji: '🎚️',
      content: [
        'Add an "almost here" warning when the bus is one stop away.',
        'Let the user pick any of the 8 stops, not just Home/School.',
        'Show the next two buses, not just the nearest one.',
      ] as string[],
      studentContent: [
        '⚠️ Warn when the bus is 1 stop away',
        '🚏 Let the user pick any of the 8 stops',
        '🚌🚌 Show the next two buses!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a second bus on the loop and track whichever arrives first.',
        'Vary the time-per-stop to simulate traffic.',
        'Show a little map with the bus position highlighted.',
      ] as string[],
      studentContent: [
        '🚌➕ Add a 2nd bus, track the first to arrive',
        '🚦 Vary time-per-stop to simulate traffic',
        '🗺️ Highlight the bus position on a mini map',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Stops-away goes negative once the bus passes your stop',
          cause: 'Using a plain subtraction on a looped line.',
          solution: 'When boarding stop < bus location, wrap: 8 − bus location + boarding stop.',
        },
        {
          problem: 'The tracker never updates',
          cause: 'No broadcast after the bus moves.',
          solution: 'Add a "broadcast real-time bus location" after each bus custom block (1-2, 2-3, …).',
        },
        {
          problem: 'Arrival never triggers',
          cause: 'Comparison or reset issue.',
          solution: 'Check "if bus location = boarding stop", then reset boarding stop to 0 after the alert.',
        },
        {
          problem: 'Two notifications stack on screen — Suggested',
          cause: 'Screen not cleared between updates.',
          solution: 'Clear the screen at the start of the "real-time bus location" handler.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student selected a boarding stop with buttons.',
        'Student compared boarding stop and bus location.',
        'Student handled the looped stops-away maths.',
        'Student estimated arrival time (×3 min).',
        'Student notified on arrival.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'List the data a real bus app uses (location, schedule, traffic…).',
        'Why does a looped route need different maths than a straight line?',
        'Suggest one improvement to your local bus system.',
      ] as string[],
      studentContent: [
        '📊 What data does a real bus app use?',
        '🔁 Why does a loop need different maths than a line?',
        '🚌 Suggest one improvement to your local buses!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'CORE MATHS: the looped "stops away" (8 − bus + boarding) is the key idea — worth drawing on the board with the circle line.',
        'REAL-TIME PATTERN: broadcast on every bus move → handler recomputes. Reinforces the broadcast/receive idea from Lesson 3.',
        'ESTIMATION: arrival = stops × 3 min is a clean, real-world maths link.',
        'PRESET: the bus already drives the loop, so students focus on the tracker logic, not animation.',
        'DATA THEME: this closes Module 2 — every smart device has run on sensor/'
          + 'message data. Tie it together in the Evaluate discussion.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l8-r1', title: 'Lesson 8 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (bus system)', needsReview: true },
    { id: 'mb2l8-r2', title: 'Demo Program — Circle Line (.mblock)', type: 'code', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Bus loop + tracker starter', needsReview: true },
    { id: 'mb2l8-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};
