import type { Course, LessonDetail } from '@/types';

// ════════════════════════════════════════════════════════════════
//  mBot2 / CyberPi — "Coding & IoT, Part 1"
//  Converted from RoboHolic Summer Camp 2025 materials
//  (9-12 yo → Mbot2 Activities Part 1). Lesson plans by Makeblock.
// ════════════════════════════════════════════════════════════════
export const MBOT2_COURSE: Course = {
  id: 'mbot2-iot-1',
  slug: 'coding-and-iot-part-1',
  title: 'mBot2 Coding & IoT — Part 1',
  programId: 'mbot2',
  programSlug: 'mbot2',
  ageGroup: '10-12',
  level: 'Intermediate',
  description:
    'Students use the CyberPi controller and mBlock to build real smart devices — from a noise detector to a houseplant carer and a self-driving vehicle. Each project follows the 5E model (Engage, Explore, Explain, Elaborate, Evaluate) and connects coding to everyday life.',
  objectives: [
    'Use CyberPi sensors to retrieve real-world data',
    'Display data and feedback on the CyberPi screen and LEDs',
    'Use variables, conditionals, and broadcasts in mBlock',
    'Connect computing concepts to real-life problems',
    'Design, build, test, and present a working smart device',
  ],
  duration: '14 sessions × 45 minutes',
  totalHours: 10.5,
  lessonCount: 14,
  prerequisites: ['Comfortable with block-based coding', 'Basic knowledge of sensors'],
  skills: ['Sensors & Data', 'Variables', 'Conditionals', 'IoT Thinking', 'Problem Solving'],
  modules: [
    {
      id: 'mb2-m1',
      title: 'Module 1: Sensing the World',
      description: 'Read sensor data and respond to the environment.',
      order: 1,
      lessons: [
        { id: 'mbot2-l1', title: 'Noise Detector',          duration: '45 min', difficulty: 2, skills: ['Sound Sensor', 'Data', 'Conditionals'], order: 1 },
        { id: 'mbot2-l2', title: 'Voice Reactive Lights',    duration: '45 min', difficulty: 2, skills: ['Sound Sensor', 'LEDs', 'Mapping'],      order: 2 },
        { id: 'mbot2-l3', title: 'Remote Classroom Polling', duration: '45 min', difficulty: 3, skills: ['Wireless', 'Broadcast', 'Data'],        order: 3 },
        { id: 'mbot2-l4', title: 'Houseplant Care',          duration: '45 min', difficulty: 3, skills: ['Sensors', 'Thresholds', 'IoT'],         order: 4 },
      ],
    },
    {
      id: 'mb2-m2',
      title: 'Module 2: Smart Devices',
      description: 'Build devices that make decisions and notify people.',
      order: 2,
      lessons: [
        { id: 'mbot2-l5', title: 'Smart Notifier',     duration: '45 min', difficulty: 3, skills: ['Notifications', 'Logic'],       order: 5 },
        { id: 'mbot2-l6', title: 'Parcel Locker',       duration: '45 min', difficulty: 3, skills: ['Passwords', 'Security', 'Logic'], order: 6 },
        { id: 'mbot2-l7', title: 'Intelligent Vehicles', duration: '45 min', difficulty: 4, skills: ['Motors', 'Autonomy', 'Sensors'], order: 7 },
        { id: 'mbot2-l8', title: 'Bus Tracker',         duration: '45 min', difficulty: 3, skills: ['Real-time Data', 'Display'],     order: 8 },
      ],
    },
    {
      id: 'mb2-m3',
      title: 'Module 3: Games & Interaction',
      description: 'Use sensors and the screen to build interactive games.',
      order: 3,
      lessons: [
        { id: 'mbot2-l9',  title: 'Colors Hunter',            duration: '45 min', difficulty: 3, skills: ['Color Sensor', 'Game Logic'], order: 9 },
        { id: 'mbot2-l10', title: 'Opposite Game',            duration: '45 min', difficulty: 3, skills: ['Logic', 'Reaction'],          order: 10 },
        { id: 'mbot2-l11', title: 'Catch Fish Carnival I',    duration: '45 min', difficulty: 4, skills: ['Game Design', 'Variables'],   order: 11 },
        { id: 'mbot2-l12', title: 'Catch Fish Carnival II',   duration: '45 min', difficulty: 4, skills: ['Game Design', 'Scoring'],     order: 12 },
        { id: 'mbot2-l13', title: 'Dodge the Bird I',         duration: '45 min', difficulty: 4, skills: ['Game Loop', 'Collision'],     order: 13 },
        { id: 'mbot2-l14', title: 'Dodge the Bird II',        duration: '45 min', difficulty: 5, skills: ['Game Polish', 'Levels'],      order: 14 },
      ],
    },
  ],
};

// ─── Lesson 1: Noise Detector — Full Detail ──────────────────────
// Source: "Lesson 01_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_1: LessonDetail = {
  id: 'mbot2-l1',
  slug: 'noise-detector',
  title: 'Noise Detector',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 2,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Sound Sensor', 'Data & Variables', 'Conditionals', 'LEDs & Screen', 'IoT Thinking'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                          quantity: '1 per student or pair' },
    { item: 'Pens and paper (for the survey)',      quantity: '1 per student' },
    { item: 'Visual Aids slides (projector)',       quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Identify the basic characteristics and types of data.',
    'Explain the importance and common uses of data in everyday life.',
    'Use a sensor to retrieve data and display it on the screen.',
    'Write a program that creates a working noise detector.',
  ],
  assessmentChecklist: [
    'Student can give examples of different types of data (images, sounds, text, numbers).',
    'Student connected CyberPi to mBlock and read the sound-volume sensor.',
    'Student stored the volume in a variable and displayed it on the screen.',
    'Student used a conditional + threshold to trigger an alert (red LEDs + "Please be quiet").',
    'Student described a real situation where a noise detector would be useful.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Install mBlock on each laptop and confirm it connects to a CyberPi (USB or Bluetooth).',
        'Charge / check every CyberPi kit. Have at least one spare ready.',
        'Open the "Lesson 01 Visual Aids" slides on the projector — the lesson refers to specific slides.',
        'Build the finished Noise Detector yourself first so you can demo it and anticipate issues.',
        'Print or prepare pens & paper for the opening in-class survey.',
        'Prerequisites to keep in mind: students should already be comfortable with block-based coding and the basic idea of a sensor.',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–8: Hand out pens & paper; students work in pairs and survey classmates with 3 questions (e.g. "Where would you like to spend your weekends?", "How many times do you visit the library per month?", "Have you seen any uncivil behaviour?"). Give 1 minute, then pick 2–3 pairs to share.',
          tip: 'Then ask "What is data?" Explain that all those answers ARE data — data is distinct information (birthday, height, hobby…) that comes as images, sounds, text, symbols and numbers.',
          coachNote: 'Goal of this section: students feel that data is everywhere and useful — don\'t rush to the robot yet.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 10–11: Introduce a scenario where noise is annoying — e.g. "You\'re on a bus and someone is talking very loudly. How do you feel?" Then: "Imagine a device that monitors the sound around us. What features must it have?" Pairs discuss 1 minute; pick 2 students to share.',
          tip: 'Write the suggested features on the board — you\'ll turn them into a mind map next.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 13–16: Show how a noise detector works. Together with the class, analyse the features it needs and draw a mind map (detect sound → decide if too loud → warn).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 18–28: Show where the modules are on CyberPi (LED screen, buttons, joystick, sensors, LED indicators). Help students start CyberPi, connect it in mBlock, and add the CyberPi device. Then build the program in stages — see the Main Activity below.',
          coachNote: 'This is the heart of the lesson. Move through it in small steps and let students test after each stage.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slides 30–31: Pick 1–2 students to demo their noise detector. Discuss: "Where would a noise detector be useful? When should we watch our own volume?" Finish with: "What other uses of data can you think of in daily life?"',
          tip: 'Tie it back to the opening survey — bring the lesson full circle from data → device → real life.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Noise Detector! 🔊',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Noise Detector! 🔊',
      content: [
        'Do the quick class survey with your partner — you\'re collecting DATA!',
        'Connect your CyberPi to mBlock.',
        'Use the sound sensor to read the volume around you.',
        'Show the volume number on the CyberPi screen.',
        'Make a rule: if it gets too loud, flash red LEDs and show "Please be quiet".',
        'Test it — shout, clap, whisper. Does it react?',
        'Show your detector to the class!',
      ] as string[],
      studentContent: [
        '📋 Collect data with the class survey',
        '🔌 Connect CyberPi to mBlock',
        '🎤 Read the sound volume with the sensor',
        '🖥️ Show the volume on the screen',
        '🚨 If too loud → red LEDs + "Please be quiet"',
        '🧪 Test it: shout, clap, whisper!',
        '🎉 Show off your noise detector!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Noise Detector',
      emoji: '🛠️',
      content: [
        'Build the program in 3 stages — have students test after each one.',
        'STAGE 1 — Display the volume: Use CyberPi\'s sound sensor to read "loudness". Clear the screen first, then print the volume value. Tip: the raw value fluctuates fast, so store it in a variable named "volume" to make it readable.',
        'STAGE 2 — Make a decision: Add a conditional that checks the volume against a threshold (the example uses 40, but students can choose their own). If the volume is above the threshold, broadcast an "alert" message.',
        'STAGE 3 — Define alert vs. standby: On "alert" → LEDs blink red AND the screen shows "Please be quiet". On standby (volume below threshold) → LEDs off and the warning text disappears.',
        'Once all three stages work together, the device continuously listens and reacts in real time.',
      ] as string[],
      studentContent: [
        '1️⃣ Read the volume and show it on screen (store it in a "volume" variable so it\'s steady)',
        '2️⃣ Add a rule: IF volume > 40 → send an "alert"',
        '3️⃣ On alert: 🔴 LEDs blink red + screen says "Please be quiet"',
        '4️⃣ When quiet again: LEDs off, message gone',
        '✅ Put it all together — your detector now reacts live!',
      ],
      images: [
        { src: '/lessons/mbot2-l1/program-full.png', kind: 'block', caption: 'The complete Noise Detector program in mBlock — build it stage by stage.' },
        { src: '/lessons/mbot2-l1/block-led-display.png', kind: 'block', caption: 'The "LED displays colour" block — pick the alert colour (red).' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Tune Your Detector',
      emoji: '🎚️',
      content: [
        'Change the threshold value and test it. What number works best for your classroom?',
        'Add a second level: a yellow "getting loud" warning before the red "too loud" alert.',
        'Make the alert friendlier or funnier — change the message or add a sound.',
      ] as string[],
      studentContent: [
        '🎚️ Change the loudness limit — what number is best?',
        '🟡 Add a "getting loud" yellow warning before red',
        '😄 Make your alert message fun!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Count how many times the room got "too loud" during the lesson and show the count on the screen.',
        'Use the joystick or buttons to let the user change the threshold without editing the code.',
        'Discuss: how could this become a real product for a library or hospital?',
      ] as string[],
      studentContent: [
        '🔢 Count how many times it got too loud and show the total',
        '🕹️ Use the buttons/joystick to change the limit live',
        '💡 How could this be a real product for a library?',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'The volume number on screen changes too fast to read',
          cause: 'The sound sensor updates continuously, so the raw value fluctuates every instant.',
          solution: 'Store the reading in a variable named "volume" and display the variable. Optionally add a short wait in the loop to slow updates.',
        },
        {
          problem: 'CyberPi won\'t connect to mBlock',
          cause: 'Device not added, wrong connection mode, or driver/Bluetooth issue.',
          solution: 'In mBlock, click "Add" and choose CyberPi, then Connect (USB or Bluetooth). Re-seat the USB cable, and make sure the CyberPi is powered on.',
        },
        {
          problem: 'Old text stays on the screen behind the new text',
          cause: 'The screen was not cleared before printing.',
          solution: 'Add the "clear screen" block at the start of the loop so each update shows cleanly. (Note: the standby step already clears it — don\'t clear twice.)',
        },
        {
          problem: 'LEDs stay red even when it\'s quiet — Suggested',
          cause: 'No standby branch, so the alert state is never reset.',
          solution: 'Make sure the ELSE / standby path turns the LEDs off and removes the warning text when volume is below the threshold.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student can give examples of different types of data.',
        'Student connected CyberPi and read the sound sensor.',
        'Student displayed the volume using a variable.',
        'Student used a threshold + conditional to trigger an alert.',
        'Student demonstrated the working detector and explained a real use.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Find 3 places in your home or neighbourhood where a noise detector would be useful. Write down what the "too loud" limit should be for each.',
        'List 3 other kinds of data you meet every day (e.g. a weather report, bus arrival times, a step counter) and what problem each one helps solve.',
        'Optional: sketch an upgrade for your detector and bring the idea next lesson.',
      ] as string[],
      studentContent: [
        '🏠 Find 3 places a noise detector would help — what\'s the right limit for each?',
        '📊 List 3 kinds of data you see every day and what they\'re for',
        '✏️ Sketch one upgrade idea for next time!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'BIG IDEA: The lesson is really about DATA — the noise detector is the hook. Keep linking "sensor reading" back to "this is data".',
        'THRESHOLD: 40 is just the example value. Encourage students to experiment — owning the number increases engagement.',
        'PACING: The 20-minute Elaborate build is the core. If short on time, trim the survey/discussion, not the build.',
        'DATA VARIABLE: The "store volume in a variable" trick is the key teaching moment — make sure everyone sees why the raw value is hard to read.',
        'REAL-WORLD TIE-IN: Libraries, hospitals, exam halls, cinemas are great discussion examples for where this matters.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l1-r1', title: 'Lesson 1 Visual Aids (Slides)',  type: 'slides', audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides referenced in the plan', needsReview: true },
    { id: 'mb2l1-r2', title: 'Demo Program (.mblock)',          type: 'code',   audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Finished noise detector program',        needsReview: true },
    { id: 'mb2l1-r3', title: 'Original Lesson Plan (PDF)',      type: 'pdf',    audience: 'coach',   url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan',             needsReview: true },
  ],
};

// ─── Lesson 2: Voice Reactive Lights — Full Detail ───────────────
// Source: "Lesson 02_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_2: LessonDetail = {
  id: 'mbot2-l2',
  slug: 'voice-reactive-lights',
  title: 'Voice Reactive Lights',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 2,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Sound Sensor', 'LEDs & Colour', 'Bar Charts', 'Variables', 'Mind Mapping'],
  materials: [
    { item: 'Laptop/desktop with mBlock 5 installed', quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                            quantity: '1 per student or pair' },
    { item: 'Speakers / music to play (Evaluate)',    quantity: '1 per classroom', isOptional: true },
    { item: 'Visual Aids slides (projector)',         quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Display a bar chart on the CyberPi screen.',
    'Change lighting effects and the bar chart based on the sound level.',
    'Use a mind map to analyse how to complete a project.',
    'Write a program that creates the Voice Reactive Lights project.',
  ],
  assessmentChecklist: [
    'Student detected the sound level using the sound sensor.',
    'Student changed LED colour and brightness based on volume.',
    'Student displayed sound levels as a bar chart on the screen.',
    'Student used variables to make multiple bars with different heights.',
    'Student presented their Voice Reactive Lights to the group.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Install mBlock 5 and confirm each laptop connects to a CyberPi in Upload mode.',
        'Open the Lesson 2 Visual Aids slides — they include musical-fountain pictures and a video used in Engage.',
        'Build the finished Voice Reactive Lights project yourself so you can demo it.',
        'Have music ready to play for the Evaluate showcase at the end.',
        'Prerequisite: students should already know CyberPi\'s main features and how to read its sensors (from Lesson 1).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–4: Show pictures/video comparing traditional fountains and musical fountains. Ask "Which do you like and why?" Then introduce how musical fountains work.',
          tip: 'Play a short musical-fountain video clip if you have one — it instantly sells the idea.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slide 6: Ask "How do the music, fountain, and lighting fit together?" Guide them to the rule: louder music → darker colour, higher spout, faster changes; softer music → lighter colour, lower spout, slower changes.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 8–9: Explain that although we can\'t build a real fountain, we can use CyberPi to make Voice Reactive Lights. Analyse the features together and draw a mind map (detect sound → set lights → draw bars).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 11–17: Connect the device and select Upload mode. Demonstrate reading the sound level, then build the program in two parts — lighting effects, then the volume bar chart. See the Main Activity below.',
          coachNote: 'Tip from the plan: have students add the "wait" block, then remove it, and compare — it shows why timing matters for smooth effects.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 19: Play music and invite students to present. Have them demo in small groups first, then ask volunteers to present to the whole class.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Make Lights Dance to Sound! 🎶',
      emoji: '🎯',
      studentTitle: 'Your Mission: Make Lights Dance to Sound! 🎶',
      content: [
        'Connect your CyberPi and switch to Upload mode.',
        'Read the sound level with the sound sensor.',
        'Make the LEDs change colour and brightness with the volume.',
        'Draw a bar chart on the screen that grows with the sound.',
        'Use variables to show four bars at different heights.',
        'Play music and watch your lights dance!',
      ] as string[],
      studentContent: [
        '🔌 Connect CyberPi (Upload mode)',
        '🎤 Read the sound level',
        '🌈 LEDs change colour + brightness with volume',
        '📊 Draw a bar chart that grows with the sound',
        '🔢 Use variables for 4 different bars',
        '🎶 Play music — watch them dance!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Build the Voice Reactive Lights',
      emoji: '🛠️',
      content: [
        'PART A — Lighting effects: Use the "set LED colour (RGB)" block (each colour 0–255; higher = brighter) and the "set brightness" block (0–100). Use "pick random () to ()" for the RGB values so colours change, and add a short "wait () seconds" between changes for a smooth transition. The lights start changing as soon as the program runs.',
        'PART B — Bar chart on screen: Use the "bar chart, add data" block to show the sound level. Set a different "brush colour" before each bar, otherwise all the data stacks into one bar.',
        'PART C — Different heights: To make bars of different heights, collect the volume into separate variables (Volume1–Volume4) at short intervals, then draw one coloured bar per variable.',
        'Run the lighting script and the bar-chart script from the SAME event block so they start together.',
      ] as string[],
      studentContent: [
        '🌈 PART A: LED colour with random RGB + a short wait for smooth changes',
        '📊 PART B: "bar chart, add data" with a different brush colour per bar',
        '🔢 PART C: store Volume1–4 in variables, then draw 4 coloured bars',
        '▶️ Start both scripts from the SAME event block so they run together!',
      ],
      images: [
        { src: '/lessons/mbot2-l2/blocks-bar-chart.png',   kind: 'block', caption: 'Set a brush colour before each "bar chart, add data" block — otherwise bars merge.' },
        { src: '/lessons/mbot2-l2/blocks-volume-vars.png', kind: 'block', caption: 'Collect the volume into Volume1–4 every 0.02s so each bar can differ.' },
        { src: '/lessons/mbot2-l2/program-bars-final.png', kind: 'block', caption: 'The finished script: four coloured bars driven by the four volume variables.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Make It Yours',
      emoji: '🎚️',
      content: [
        'Add the "wait" block, then remove it, and compare how the effect changes. Which feels better?',
        'Change the colour scheme so louder = darker (like the musical-fountain rule).',
        'Add more bars, or make the bars taller for louder sounds.',
      ] as string[],
      studentContent: [
        '⏱️ Try adding and removing the "wait" — which looks better?',
        '🎨 Make louder sounds = darker colours',
        '📈 Add more bars or make them taller!',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Map the volume to spout "height" by changing how tall the tallest bar can grow.',
        'Add a "beat" feel: flash all LEDs white on the loudest peaks.',
        'Design a 30-second light show synced to a specific song.',
      ] as string[],
      studentContent: [
        '🌊 Make the tallest bar represent a fountain "spout"',
        '💥 Flash white on the loudest peaks',
        '🎵 Design a 30-second light show for a song!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'All the bars merge into one bar',
          cause: 'Every "bar chart, add data" used the same brush colour.',
          solution: 'Set a different brush colour before each bar. Same colour = the data is treated as one bar.',
        },
        {
          problem: 'The bars all have the same height',
          cause: 'The same value is used for each bar instead of separate readings.',
          solution: 'Store the volume into separate variables (Volume1–4) at short intervals, then draw each variable as its own bar.',
        },
        {
          problem: 'Lighting and bar chart are out of sync',
          cause: 'The two scripts start from different event blocks.',
          solution: 'Start both scripts from the same Event block so they run together.',
        },
        {
          problem: 'Light changes look jumpy — Suggested',
          cause: 'No transition time between colour changes.',
          solution: 'Add a short "wait () seconds" between changes; tune the value until the transition looks smooth.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student read the sound level with the sensor.',
        'Student changed LED colour/brightness from the volume.',
        'Student displayed sound as a bar chart.',
        'Student used variables for bars of different heights.',
        'Student presented their project.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Find a real place that uses lights + sound together (concert, fountain, game) and note how they connect.',
        'Sketch your dream light show: what colours happen at quiet vs. loud moments?',
        'Optional: plan which song you\'d sync your lights to next time.',
      ] as string[],
      studentContent: [
        '🔦 Find a real place that mixes lights + sound — how do they connect?',
        '🎨 Sketch your dream light show (quiet vs. loud)',
        '🎵 Pick a song to sync next time!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'BIG IDEA: This builds directly on Lesson 1 — the sound sensor again, but now driving richer output (colour + a live chart).',
        'KEY MISTAKE TO PRE-EMPT: same brush colour → merged bars. Show this on purpose, then fix it together.',
        'VARIABLES MOMENT: collecting Volume1–4 is the core concept — it\'s why bars can differ. Make sure everyone gets it.',
        'PACING: Lighting (Part A) is quick and rewarding; the bar chart (Parts B–C) is the harder part — leave most of the 20 min for it.',
        'SHOWCASE: the music + present finish is high-energy — protect the last 5 minutes for it.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l2-r1', title: 'Lesson 2 Visual Aids (Slides)', type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (fountains, video)', needsReview: true },
    { id: 'mb2l2-r2', title: 'Demo Program (.mblock)',         type: 'code',   audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Finished Voice Reactive Lights program', needsReview: true },
    { id: 'mb2l2-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 3: Remote Classroom Polling — Full Detail ────────────
// Source: "Lesson 03_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_3: LessonDetail = {
  id: 'mbot2-l3',
  slug: 'remote-classroom-polling',
  title: 'Remote Classroom Polling',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['LAN / Wi-Fi', 'Broadcast & Receive', 'Variables', 'Bar Charts', 'Data Analysis'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed',     quantity: '1 per student or pair' },
    { item: 'CyberPi kit (≥2 boards to demo LAN)',       quantity: '2+ per classroom' },
    { item: 'Visual Aids slides (projector)',            quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Describe the features of a LAN, and broadcast and receive data over it.',
    'Generate a bar chart based on the votes.',
    'Analyse poll results and draw conclusions.',
    'Use a mind map to plan a remote classroom polling system.',
    'Write the programs that complete the polling project.',
  ],
  assessmentChecklist: [
    'Student can explain what a LAN is and how it differs from the Internet.',
    'Student broadcast and received a message over Wi-Fi/LAN between CyberPi boards.',
    'Student used a variable (VotingStatus) so each voter votes only once.',
    'Student counted votes with a conditional and displayed a bar chart.',
    'Student interpreted the result chart and drew a conclusion.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'You need at least TWO CyberPi boards to demonstrate LAN broadcasting (one initiator, one voter).',
        'In mBlock, you write two programs: select "CyberPi" (initiator) and "CyberPi 2" (voter) under Devices. Select Upload mode.',
        'Build and test both programs in advance — this is the most complex lesson in the module.',
        'Prepare a few fun poll questions (favourite song, movie star, game) for the live vote.',
        'Prerequisites: students can write block programs and know CyberPi\'s main features (Lessons 1–2).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–5: Ask about voting in competition shows — how does the live audience vote? Could people at home join? Introduce LAN: a closed, local network where only connected devices can share information (unlike the open Internet).',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 7–8: "We\'ll use CyberPi to form a LAN and run a poll — only this classroom can vote." Discuss the roles: an initiator starts the poll, the rest are voters, and when voting closes the initiator counts the votes.',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 10–13: Demonstrate how the polling works and draw a mind map of the features (start poll → send options → cast votes → count → show results).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 15–26: Build TWO programs — initiator and voter — see the Main Activity. Use LAN "broadcast" / "when receiving … on Wi-Fi" blocks to communicate, a VotingStatus variable so each voter votes once, and a bar chart to show results.',
          coachNote: 'Edge case from the plan: if two boards send the same message on the LAN at the exact same instant, the receiver counts it once — but this is rare. Mention it only if asked.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 29: Run a real classroom poll (e.g. favourite song). When done, have students read the result chart and explain WHY the winner is popular.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Classroom Voting System! 🗳️',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Classroom Voting System! 🗳️',
      content: [
        'Learn what a LAN is — a private network just for this room.',
        'Program the INITIATOR board to start the poll and send the options.',
        'Program the VOTER board to show options and send a vote with the joystick.',
        'Make sure each voter can only vote once (use a VotingStatus variable).',
        'Count the votes on the initiator and show a bar chart.',
        'Run a real poll and read the results!',
      ] as string[],
      studentContent: [
        '📡 Learn what a LAN is (a private network for our room)',
        '▶️ INITIATOR: start the poll + send the options',
        '🕹️ VOTER: show options, vote with the joystick',
        '☝️ One vote each — use a VotingStatus variable',
        '📊 Count votes + show a bar chart',
        '🏆 Run a real poll and read the winner!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Build the Polling System (2 boards)',
      emoji: '🛠️',
      content: [
        'INITIATOR — start the poll: Create two variables for the option tallies and set both to 0. Broadcast "options" on Wi-Fi, show "Options sent. Poll starts", and set a timer for the voting period.',
        'VOTER — display options: "when receiving options broadcast on Wi-Fi" → clear screen and print the choices (e.g. Option A = joystick pulled ↑, Option B = pulled ↓).',
        'VOTER — cast a vote: Use a VotingStatus variable (0 = not voted). Repeat until voted: if the joystick is pulled, broadcast "vote" with the chosen value, show a confirmation, and set VotingStatus to 1 so they can\'t vote again.',
        'INITIATOR — count votes: "when receiving vote on Wi-Fi" during the voting period → check the received value and add 1 to the matching option\'s tally.',
        'INITIATOR — show results: When a button is pressed, display the tally as text and a bar chart (different colour per bar). Tip: add a base number to each tally so small results still look clear.',
      ] as string[],
      studentContent: [
        '▶️ INITIATOR: set both tallies to 0, broadcast "options", start a timer',
        '🕹️ VOTER: show options, then vote by pulling the joystick',
        '☝️ Use VotingStatus so you can only vote once',
        '🔢 INITIATOR: count each "vote" message into the right tally',
        '📊 Press a button to show the results as a bar chart!',
      ],
      images: [
        { src: '/lessons/mbot2-l3/voter-display-options.png',   kind: 'block', caption: 'VOTER: when "options" is received, show the choices on screen.' },
        { src: '/lessons/mbot2-l3/voter-cast-vote.png',         kind: 'block', caption: 'VOTER: pull the joystick to broadcast a "vote"; VotingStatus stops double-voting.' },
        { src: '/lessons/mbot2-l3/initiator-count-results.png', kind: 'block', caption: 'INITIATOR: on button press, tally the votes and draw a bar chart.' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Complete the System',
      emoji: '🎚️',
      content: [
        'The example handles one option — extend it so BOTH options are sent, counted, and charted.',
        'Show both result bars in different colours at the same time.',
        'Add a clear "poll closed" message when the timer ends.',
      ] as string[],
      studentContent: [
        '➕ Make it work for BOTH options (not just one)',
        '🎨 Show both result bars in different colours',
        '⏰ Add a "poll closed!" message when time runs out',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a third option and a third joystick direction.',
        'Show live results that update as votes come in.',
        'Calculate and display the winning percentage, not just the count.',
      ] as string[],
      studentContent: [
        '3️⃣ Add a third option (and joystick direction)',
        '⚡ Show results updating live as votes arrive',
        '📈 Show the winning percentage, not just the count!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Voter board receives nothing',
          cause: 'The broadcast names don\'t match, or boards aren\'t on the same LAN.',
          solution: 'Make sure the "when receiving (…)" name is spelled exactly like the broadcast sent, and both boards joined the same Wi-Fi/LAN.',
        },
        {
          problem: 'A student can vote many times',
          cause: 'No VotingStatus check.',
          solution: 'Create a VotingStatus variable (0 = not voted). After a vote, set it to 1 and only allow voting while it is 0.',
        },
        {
          problem: 'Votes counted for the wrong option',
          cause: 'The conditional that checks the received value is missing or wrong.',
          solution: 'Check the broadcast value and add 1 to the matching tally. Build option A first, then duplicate the logic for option B.',
        },
        {
          problem: 'Bar chart is hard to read with few votes — Suggested',
          cause: 'Small numbers make tiny bars.',
          solution: 'Add a base number to each tally (e.g. value + 10) so the bars are clearly visible.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student explained what a LAN is.',
        'Student broadcast and received messages between boards.',
        'Student prevented double-voting with a variable.',
        'Student counted votes and drew a bar chart.',
        'Student interpreted the results.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'List 3 real systems that use voting or polling and how they collect the data.',
        'Write a poll question you\'d like to run in class and predict the result.',
        'Reflect: why might a closed LAN be safer than the open Internet for a classroom vote?',
      ] as string[],
      studentContent: [
        '🗳️ Find 3 real voting/polling systems — how do they collect data?',
        '❓ Write a poll question and predict the winner',
        '🔒 Why is a closed LAN safer than the open Internet for voting?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'HARDEST LESSON in the module — two programs on two boards. Build both yourself first.',
        'TEACH THE PATTERN: broadcast (send) ↔ when receiving (listen). Everything hinges on matching names.',
        'VotingStatus is the key concept — it\'s how we stop double votes. Spend time here.',
        'SCAFFOLD: the example does one option; completing the second is the main student challenge — pair students if needed.',
        'PAYOFF: the live class poll at the end is the motivator — leave time for it and make it fun.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l3-r1', title: 'Lesson 3 Visual Aids (Slides)',          type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (voting, LAN)', needsReview: true },
    { id: 'mb2l3-r2', title: 'Demo Programs — Initiator & Voter (.mblock)', type: 'code', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Both finished CyberPi programs', needsReview: true },
    { id: 'mb2l3-r3', title: 'Original Lesson Plan (PDF)',             type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};

// ─── Lesson 4: Houseplant Care — Full Detail ─────────────────────
// Source: "Lesson 04_Lesson Plan.docx" (Makeblock CyberPi curriculum).
export const MBOT2_LESSON_4: LessonDetail = {
  id: 'mbot2-l4',
  slug: 'houseplant-care',
  title: 'Houseplant Care',
  programId: 'mbot2',
  programSlug: 'mbot2',
  programTitle: 'mBot2 / CyberPi',
  programColor: '#2563EB',
  courseId: 'mbot2-iot-1',
  courseTitle: 'mBot2 Coding & IoT — Part 1',
  moduleId: 'mb2-m1',
  moduleTitle: 'Module 1: Sensing the World',
  ageGroup: '10-12',
  level: 'Intermediate',
  duration: '45 minutes',
  difficulty: 3,
  heroImage: '/lessons/mbot2-l1/cyberpi-device.png',
  skills: ['Light Sensor', 'Variables & Maths', 'Conditions & Alarms', 'Bar Charts', 'Simulation'],
  materials: [
    { item: 'Laptop/desktop with mBlock installed',  quantity: '1 per student or pair' },
    { item: 'CyberPi kit',                            quantity: '1 per student or pair' },
    { item: 'Example program file (3 plant sprites)', quantity: 'shared by coach' },
    { item: 'Visual Aids slides (projector)',         quantity: '1 per classroom', isOptional: true },
  ],
  objectives: [
    'Explain the relationship between plants and water, and that different plants need different amounts.',
    'Simulate sunlight and monitor plant moisture with sensors.',
    'Send an alarm when water is insufficient or excessive.',
    'Use a mind map to analyse how a plant-monitoring device works.',
  ],
  assessmentChecklist: [
    'Student created a "light" variable from the light sensor.',
    'Student simulated water loss using moisture variables and division (different speeds per plant).',
    'Student displayed the three moisture levels as a bar chart (rounded to integers).',
    'Student sent an alarm when moisture went too low (<50) or too high (>110).',
    'Student used the joystick (choice variable) to select and water a plant.',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'This project runs in mBlock LIVE mode (the stage drives the simulation) and uses an example program with three plant sprites — Cactus7, Pot plant12, Pot plant1.',
        'Have the example program ready to distribute, and open it yourself first.',
        'The three plants dry out at different speeds: Cactus (slow), Pot plant12 (medium), Pot plant1 (fast).',
        'Connect each CyberPi and switch mBlock to Live mode.',
        'Prerequisites: students can write block programs and know CyberPi\'s features (Lessons 1–3).',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions (5E Model)',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'ENGAGE (5–10 min) · Slides 3–7: Discuss why plants need water and that different plants need different amounts (cacti monthly, big-leaf plants daily, most plants weekly). Ask "What happens if we water too much or forget?" — both can kill a plant, and overwatering wastes water.',
        },
        {
          step: 2,
          instruction: 'EXPLORE (5 min) · Slides 9–11: Introduce the challenge — design a device that reminds plant lovers to water correctly. Ask what features it needs (detect a moisture problem; remind the user).',
        },
        {
          step: 3,
          instruction: 'EXPLAIN (5 min) · Slides 13–15: Show the desired outcome and have students draw a mind map of the device\'s functions (sense → simulate water loss → show moisture → alarm → water).',
        },
        {
          step: 4,
          instruction: 'ELABORATE (20 min) · Slides 17–33: Connect CyberPi in Live mode and open the example. Build the project in stages — simulate water loss, show moisture, raise alarms, and add joystick watering. See the Main Activity.',
          coachNote: 'Assume all three plants get the same sunlight. The DIFFERENT divisor per plant is what makes them dry at different speeds — that\'s the core maths idea.',
        },
        {
          step: 5,
          instruction: 'EVALUATE (5 min) · Slide 35: Students present their projects and give each other feedback. Ask each to introduce a real plant (name, features, care) — encourage quick online research.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build a Plant Carer! 🌱',
      emoji: '🎯',
      studentTitle: 'Your Mission: Build a Plant Carer! 🌱',
      content: [
        'Use the light sensor to simulate sunlight drying the plants.',
        'Give each of the 3 plants its own moisture level that drops over time.',
        'Make thirsty plants dry faster and tough plants dry slower (using division).',
        'Show all 3 moisture levels as a bar chart.',
        'Sound an alarm if a plant is too dry or overwatered.',
        'Use the joystick to pick a plant and water it!',
      ] as string[],
      studentContent: [
        '☀️ Use the light sensor to simulate sunlight',
        '💧 Give each of 3 plants its own moisture level',
        '➗ Thirsty plants dry faster (smaller divisor!)',
        '📊 Show all 3 moisture levels as bars',
        '🚨 Alarm if too dry (<50) or overwatered (>110)',
        '🕹️ Joystick: pick a plant and water it!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Program the Plant Monitor',
      emoji: '🛠️',
      content: [
        'SIMULATE WATER LOSS: Create a "light" variable from the light sensor. Give each plant a moisture variable (moisture1–3) starting at 100. In a forever loop, while moisture > 0, subtract light ÷ divisor. Use a DIFFERENT divisor per plant — Cactus7 = 30 (slow), Pot plant12 = 20 (medium), Pot plant1 = 10 (fast). Add a "wait" so it doesn\'t drop too quickly, and keep moisture above 0.',
        'SHOW MOISTURE: Draw a bar chart of the three moisture levels, a different brush colour per plant. Use "round" because CyberPi only displays integers.',
        'RAISE ALARMS: If moisture < 50 the plant lacks water; if moisture > 110 it\'s overwatered. When either is true, light up an indicator. When moisture returns to normal, turn the alarm off. (Students can tune these numbers.)',
        'WATER WITH THE JOYSTICK: Create a "choice" variable limited to 1–3 to pick a plant (an arrow sprite shows which). Pull the joystick down to water the selected plant (increase its moisture).',
      ] as string[],
      studentContent: [
        '➗ Each plant loses water = light ÷ its divisor (30 / 20 / 10)',
        '📊 Show the 3 moisture levels as a rounded bar chart',
        '🚨 Alarm when moisture < 50 (dry) or > 110 (overwatered)',
        '🕹️ "choice" (1–3) picks a plant; pull down to water it',
      ],
      images: [
        { src: '/lessons/mbot2-l4/script-water-loss.png',     kind: 'block', caption: 'Water loss: subtract light ÷ divisor each second (smaller divisor = dries faster).' },
        { src: '/lessons/mbot2-l4/script-moisture-chart.png', kind: 'block', caption: 'Show all three moisture levels as a coloured bar chart (rounded to integers).' },
        { src: '/lessons/mbot2-l4/script-select-plant.png',   kind: 'block', caption: 'Use "choice" (1–3) to select a plant; an arrow glides under it.' },
        { src: '/lessons/mbot2-l4/script-water-plant.png',     kind: 'block', caption: 'Pull the joystick down to water the selected plant (raise its moisture).' },
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: Complete All Three Plants',
      emoji: '🎚️',
      content: [
        'The examples often show one plant — complete the water-loss, alarm, and indicator scripts for all three.',
        'Tune the divisors and alarm thresholds so each plant behaves realistically.',
        'Add a "healthy" green indicator when moisture is in the good range.',
      ] as string[],
      studentContent: [
        '🌵 Finish the scripts for ALL three plants',
        '🎚️ Tune each plant\'s speed and alarm limits',
        '✅ Add a green "healthy" light for the good range',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'Add a real soil-moisture sensor instead of the simulation, if you have one.',
        'Log how many times each plant needed watering during the lesson.',
        'Research a real plant and set its divisor/thresholds to match its true water needs.',
      ] as string[],
      studentContent: [
        '🌡️ Use a real moisture sensor instead of the simulation',
        '🔢 Count how many times each plant needed water',
        '🔎 Research a real plant and match its water needs!',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Moisture drops to a negative number',
          cause: 'No lower-bound check on the variable.',
          solution: 'Only subtract while "moisture > 0" so it can\'t go negative.',
        },
        {
          problem: 'All three plants dry at the same speed',
          cause: 'The same divisor was used for each plant.',
          solution: 'Use different divisors: Cactus7 = 30 (slow), Pot plant12 = 20, Pot plant1 = 10 (fast).',
        },
        {
          problem: 'Moisture drops far too fast',
          cause: 'No wait in the loop.',
          solution: 'Add a "wait () seconds" block in the loop to slow the simulation.',
        },
        {
          problem: 'Bar chart shows odd long decimals',
          cause: 'CyberPi can only display integers.',
          solution: 'Wrap the moisture value in a "round" block before charting.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment Checklist',
      emoji: '✅',
      content: [
        'Student simulated water loss with a light variable and division.',
        'Student gave each plant a different drying speed.',
        'Student displayed rounded moisture as a bar chart.',
        'Student raised alarms for too-dry / overwatered.',
        'Student watered a selected plant with the joystick.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice & Reflect',
      emoji: '🏠',
      content: [
        'Pick a real houseplant and find out how often it should be watered — what divisor would model it?',
        'Explain in your own words why overwatering can be as harmful as underwatering.',
        'Sketch a real product version of this device — where would the sensor go?',
      ] as string[],
      studentContent: [
        '🪴 Pick a real plant — how often does it need water?',
        '💭 Why is overwatering as bad as underwatering?',
        '✏️ Sketch a real version — where does the sensor go?',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'CORE MATHS IDEA: dividing the light value by a different number per plant models different drought-resistance. This is the concept to land.',
        'LIVE MODE: this project runs on the stage (sprites) in Live mode, not Upload — a good contrast with earlier lessons.',
        'SCAFFOLD: students complete the second and third plants by copying the first plant\'s pattern. Pair them if needed.',
        'GUARDRAILS: the "moisture > 0" check and the "wait" block both prevent runaway values — make sure both are in place.',
        'CROSS-CURRICULAR: great link to science (transpiration, photosynthesis) — lean into it during Engage.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'mb2l4-r1', title: 'Lesson 4 Visual Aids (Slides)',  type: 'slides', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Projector slides (plants, care)', needsReview: true },
    { id: 'mb2l4-r2', title: 'Example Program — 3 Plants (.mblock)', type: 'code', audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Starter program with the three plant sprites', needsReview: true },
    { id: 'mb2l4-r3', title: 'Original Lesson Plan (PDF)',     type: 'pdf',    audience: 'coach', url: 'https://drive.google.com/drive/folders/roboholic-mbot2', description: 'Full Makeblock lesson plan', needsReview: true },
  ],
};
