import type { Course, LessonDetail, Module } from '@/types';
import { makeKitLesson, kitSummary, type KitLesson, type KitProgram } from './_course-kit';

// Scratch (scratch.mit.edu) — visual coding: games, animations, stories.
// Interactive: every lesson has a quiz + a predict/match/fill activity (+ universal order-the-steps).
const P: KitProgram = { programId: 'scratch', programSlug: 'scratch', programTitle: 'Scratch', programColor: '#7C3AED', courseId: 'scratch-1', courseTitle: 'Code Games & Stories with Scratch' };
const L1 = 'Level I · Scratch Basics', L2 = 'Level II · Build Games', L3 = 'Level III · Advanced Projects';
const M = (item: string) => [{ item: 'Computer/tablet with a browser (scratch.mit.edu)', quantity: '1 per student' }, ...(item ? [{ item }] : [])];
const SCRATCH = { id: 'scratch-guide', title: 'Scratch — Ideas, tutorials & starter projects', type: 'link' as const, audience: 'both' as const, url: 'https://scratch.mit.edu/ideas', description: 'Official Scratch tutorials and starter projects' };

const C: KitLesson[] = [
  { id: 'sc-1', title: 'Welcome to Scratch: Sprites & the Stage', emoji: '🐱', difficulty: 1, ageGroup: '8-9', level: 'Beginner', moduleId: 'sc-m1', moduleTitle: L1, order: 1, youtubeId: 'jXUZaf5D12A',
    concept: 'the Scratch editor, sprites and blocks', conceptExplain: 'Scratch is a free block-coding language for games, animations and stories. You snap blocks together to control sprites (characters) on the stage.',
    objectives: ['Navigate the Scratch editor', 'Add a sprite and a backdrop', 'Use a "when green flag clicked" + motion block'],
    steps: ['Open scratch.mit.edu and start a project.', 'Add a sprite and a backdrop.', 'Drag "when green flag clicked" then "move 10 steps".', 'Run it with the green flag.'],
    challenge: 'Make your sprite move across the stage and say hello when clicked.', skills: ['Scratch', 'Sprites', 'Events'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'In Scratch, a "sprite" is:', options: ['the background', 'a character/object you control', 'a sound', 'a score'], answerIndex: 1 },
      { question: 'What starts a script when you click the flag?', options: ['"when green flag clicked"', '"move 10 steps"', '"say Hello"', '"forever"'], answerIndex: 0 },
      { question: 'You build programs in Scratch by:', options: ['typing text code', 'snapping blocks together', 'drawing only', 'recording video'], answerIndex: 1 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'when green flag clicked\nmove 10 steps\nmove 10 steps', question: 'What does the sprite do when you click the flag?', options: ['Nothing', 'Moves 20 steps to the right', 'Spins around', 'Says hello'], answerIndex: 1, explanation: '10 + 10 = 20 steps.' }],
  },
  { id: 'sc-2', title: 'Motion, Looks & Sequencing', emoji: '🎬', difficulty: 1, ageGroup: '8-9', level: 'Beginner', moduleId: 'sc-m1', moduleTitle: L1, order: 2,
    concept: 'sequences of motion and looks blocks', conceptExplain: 'A program is a sequence of instructions. Motion blocks move/turn the sprite; Looks blocks change costume, size and speech.',
    objectives: ['Sequence several blocks in order', 'Use motion and looks blocks', 'Add wait blocks to control timing'],
    steps: ['Chain move/turn blocks for a path.', 'Add "say" and "switch costume".', 'Insert "wait" blocks between actions.', 'Run and refine the timing.'],
    challenge: 'Animate your sprite walking across the stage and waving (costume change).', skills: ['Sequencing', 'Looks', 'Animation'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'Which category changes how a sprite LOOKS (costume, size, speech)?', options: ['Motion', 'Looks', 'Sound', 'Control'], answerIndex: 1 },
      { question: 'Running blocks one after another in order is called a:', options: ['loop', 'sequence', 'variable', 'sprite'], answerIndex: 1 },
      { question: 'A "wait 1 second" block is used to:', options: ['delete the sprite', 'control the timing', 'add a score', 'change colour'], answerIndex: 1 },
    ],
    interactions: [{ kind: 'match', title: '🔗 Match the block', pairs: [{ left: 'move 10 steps', right: 'Motion' }, { left: 'say "Hi!"', right: 'Looks' }, { left: 'play sound', right: 'Sound' }, { left: 'wait 1 second', right: 'Control' }] }],
  },
  { id: 'sc-3', title: 'Loops & Events', emoji: '🔁', difficulty: 2, ageGroup: '8-9', level: 'Beginner', moduleId: 'sc-m1', moduleTitle: L1, order: 3,
    concept: 'repetition and event-driven code', conceptExplain: 'Loops (repeat / forever) repeat actions; events (key pressed, sprite clicked, broadcast) start scripts. Together they make interactive programs.',
    objectives: ['Use repeat and forever loops', 'Trigger scripts with key/click events', 'Combine loops and events'],
    steps: ['Put motion inside a "forever" loop.', 'Add "when [space] key pressed".', 'Use "repeat 4" to move in a pattern.', 'Test with keys.'],
    challenge: 'Control a sprite with the arrow keys using four key-press events.', skills: ['Loops', 'Events', 'Interactivity'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'Which block repeats actions forever?', options: ['"forever"', '"if then"', '"say"', '"when clicked"'], answerIndex: 0 },
      { question: '"when space key pressed" is an:', options: ['event', 'loop', 'variable', 'costume'], answerIndex: 0 },
      { question: '"repeat 4" runs the blocks inside it:', options: ['once', '4 times', 'forever', 'never'], answerIndex: 1 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'repeat 4\n  move 50 steps\n  turn 90 degrees', question: 'What shape does the sprite draw/trace?', options: ['A line', 'A square', 'A circle', 'A triangle'], answerIndex: 1, explanation: '4 sides + 90° turns = a square.' }],
  },
  { id: 'sc-4', title: 'Make an Animation or Story', emoji: '📖', difficulty: 2, ageGroup: '8-9', level: 'Beginner', moduleId: 'sc-m1', moduleTitle: L1, order: 4,
    concept: 'multi-sprite stories with broadcasts', conceptExplain: 'Stories use several sprites that talk in turn. "Broadcast" messages let one sprite cue another so the conversation flows.',
    objectives: ['Use multiple sprites', 'Use broadcast to coordinate sprites', 'Build a short animated scene'],
    steps: ['Add 2–3 sprites and a backdrop.', 'Sprite 1 says a line then broadcasts "next".', 'Sprite 2 starts "when I receive next".', 'Build a 4-line animated conversation.'],
    challenge: 'Create a 2-character animated story with at least 3 broadcasts.', skills: ['Broadcasts', 'Storytelling', 'Multi-sprite'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'How does one sprite tell another to start talking?', options: ['by broadcasting a message', 'by moving', 'by changing colour', 'by waiting'], answerIndex: 0 },
      { question: '"when I receive [next]" runs when:', options: ['the flag is clicked', 'that broadcast is sent', 'a key is pressed', 'never'], answerIndex: 1 },
      { question: 'A story usually uses:', options: ['one sprite only', 'several sprites taking turns', 'no sprites', 'only sounds'], answerIndex: 1 },
    ],
    interactions: [{ kind: 'fill', title: '✏️ Fill the Blanks', intro: 'Complete the sentence about messages.', text: 'One sprite sends a message with the ___ block, and another sprite reacts using "when I ___ [message]".', answers: ['broadcast', 'receive'] }],
  },
  // Level II
  { id: 'sc-5', title: 'Variables & Score', emoji: '🔢', difficulty: 2, ageGroup: '10-12', level: 'Intermediate', moduleId: 'sc-m2', moduleTitle: L2, order: 5,
    concept: 'variables for scores and lives', conceptExplain: 'A variable stores a value like a score or lives that changes during play. You create one, set it at the start, and change it during the game.',
    objectives: ['Create a variable', 'Set and change it during play', 'Display it on the stage'],
    steps: ['Make a "score" variable, set to 0 on green flag.', 'Change score by 1 on an event.', 'Show the score on stage.', 'Test it increases.'],
    challenge: 'Make a clicker game: each click on the sprite adds 1 to the score.', skills: ['Variables', 'Scoring', 'Game Logic'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'A variable is used to:', options: ['store a value that can change (e.g. score)', 'draw a sprite', 'play music', 'change the backdrop'], answerIndex: 0 },
      { question: 'At the start of a game you usually:', options: ['set score to 0', 'delete the sprite', 'hide the stage', 'stop all sounds'], answerIndex: 0 },
      { question: '"change score by 1" does what?', options: ['sets score to 1', 'adds 1 to the score', 'shows the number 1', 'resets the game'], answerIndex: 1 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'set score to 0\nrepeat 3\n  change score by 2', question: 'What is the final score?', options: ['0', '3', '6', '2'], answerIndex: 2, explanation: '0 + 2 + 2 + 2 = 6.' }],
  },
  { id: 'sc-6', title: 'Conditionals & Collisions', emoji: '💥', difficulty: 3, ageGroup: '10-12', level: 'Intermediate', moduleId: 'sc-m2', moduleTitle: L2, order: 6,
    concept: 'if/else and "touching" detection', conceptExplain: 'Conditionals (if/else) make decisions; "touching" blocks detect collisions. Games react: if touching an enemy → lose a life.',
    objectives: ['Use if / if-else blocks', 'Detect collisions with "touching"', 'React to a condition'],
    steps: ['In a forever loop, check "if touching [sprite]".', 'On touch → change score / play sound.', 'Add an else branch.', 'Test the collision response.'],
    challenge: 'Make a "collect the stars" game where touching a star adds score and hides it.', skills: ['Conditionals', 'Collisions', 'Logic'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'Which block detects a collision?', options: ['"touching [sprite]?"', '"move 10 steps"', '"say Hi"', '"wait 1 second"'], answerIndex: 0 },
      { question: '"if ... else" lets the program:', options: ['repeat forever', 'choose between two actions', 'store a number', 'change costume'], answerIndex: 1 },
      { question: 'To keep checking for a collision you put the "if" inside a:', options: ['forever loop', 'say block', 'variable', 'backdrop'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'forever\n  if touching [Star] then\n    change score by 1\n    hide [Star]', question: 'What happens when the sprite touches the star?', options: ['Nothing', 'Score goes up by 1 and the star disappears', 'The game ends', 'The star multiplies'], answerIndex: 1 }],
  },
  { id: 'sc-7', title: 'Build a Complete Game', emoji: '🎮', difficulty: 3, ageGroup: '10-12', level: 'Intermediate', moduleId: 'sc-m2', moduleTitle: L2, order: 7,
    concept: 'a full game loop with win/lose', conceptExplain: 'A complete game has a goal, controls, scoring, and a win/lose end. You combine movement, variables, conditionals and a timer.',
    objectives: ['Combine movement, score and collisions', 'Add a timer or lives', 'Add a win/lose ending'],
    steps: ['Plan goal + controls + win/lose.', 'Code player movement and a scoring rule.', 'Add a timer or lives variable.', 'Add a "Game Over"/"You win" screen.'],
    challenge: 'Build a maze or catch game with a score, a timer, and a clear ending.', skills: ['Game Design', 'Integration', 'Variables'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'A complete game needs a:', options: ['goal and a win/lose condition', 'single sprite only', 'no controls', 'no score'], answerIndex: 0 },
      { question: 'Lives or a timer are usually stored in a:', options: ['variable', 'costume', 'sound', 'backdrop'], answerIndex: 0 },
      { question: 'Player controls are usually:', options: ['key-press events', 'broadcasts only', 'sounds', 'backdrops'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'match', title: '🔗 Match the game part', pairs: [{ left: 'Arrow keys move the player', right: 'Controls' }, { left: 'score variable', right: 'Scoring' }, { left: 'touching enemy → lose', right: 'Lose condition' }, { left: 'reach the goal → win', right: 'Win condition' }] }],
  },
  { id: 'sc-8', title: 'Clones & Spawning', emoji: '👯', difficulty: 3, ageGroup: '10-12', level: 'Intermediate', moduleId: 'sc-m2', moduleTitle: L2, order: 8,
    concept: 'clones to spawn many objects', conceptExplain: 'Clones make copies of a sprite at run-time — perfect for falling objects, bullets or enemies — without copy-pasting sprites.',
    objectives: ['Create clones at intervals', 'Give clones their own behaviour', 'Delete clones when done'],
    steps: ['Use "create clone of myself" on a timer.', 'In "when I start as a clone", move it down.', 'Delete the clone at the edge.', 'Tune the spawn rate.'],
    challenge: 'Make falling objects the player must catch or dodge using clones.', skills: ['Clones', 'Spawning', 'Game Feel'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'Clones are used to:', options: ['make many copies of a sprite at run-time', 'change the backdrop', 'store the score', 'play music'], answerIndex: 0 },
      { question: 'Code for each copy goes in:', options: ['"when I start as a clone"', '"when green flag clicked"', '"say Hi"', '"forever" only'], answerIndex: 0 },
      { question: 'To stop too many clones piling up you should:', options: ['delete the clone when done', 'add more sprites', 'hide the stage', 'mute sounds'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'forever\n  create clone of myself\n  wait 1 second', question: 'What happens over time?', options: ['Nothing', 'A new clone appears about every second', 'The sprite disappears', 'The score drops'], answerIndex: 1 }],
  },
  // Level III
  { id: 'sc-9', title: 'Lists & Data', emoji: '🗃️', difficulty: 4, ageGroup: '10-12', level: 'Advanced', moduleId: 'sc-m3', moduleTitle: L3, order: 9,
    concept: 'lists (arrays) of values', conceptExplain: 'A list stores many values under one name — quiz questions, high scores, inventory. You add, read by index, and loop over a list.',
    objectives: ['Create and fill a list', 'Read items by index', 'Use a list in a project (e.g. a quiz)'],
    steps: ['Make a list and add items.', 'Read item (i) of the list.', 'Loop through the list.', 'Use it for a quiz or high-score table.'],
    challenge: 'Build a quiz that pulls questions from a list and tracks the score.', skills: ['Lists', 'Data', 'Quiz'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'A list lets you store:', options: ['many values under one name', 'only one value', 'only the score', 'sounds only'], answerIndex: 0 },
      { question: '"item 1 of [list]" gives:', options: ['the first item', 'the whole list', 'the last item', 'a random item'], answerIndex: 0 },
      { question: 'A good use of a list is:', options: ['storing quiz questions or high scores', 'changing the backdrop', 'playing one sound', 'moving 10 steps'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'fill', title: '✏️ Fill the Blanks', intro: 'Complete the list facts.', text: 'A list holds ___ values. You add a value with the "___ to" block, and read one with "item ___ of [list]".', answers: ['many', 'add', '1'] }],
  },
  { id: 'sc-10', title: 'Custom Blocks (My Blocks)', emoji: '🧩', difficulty: 4, ageGroup: '10-12', level: 'Advanced', moduleId: 'sc-m3', moduleTitle: L3, order: 10,
    concept: 'defining your own blocks (functions)', conceptExplain: 'My Blocks let you define your own block (a function) with inputs, so you can reuse code and keep scripts tidy — a key step toward real programming.',
    objectives: ['Define a custom block with an input', 'Call it with different values', 'Refactor repeated code into a block'],
    steps: ['Make a block e.g. "draw star (size)".', 'Define what it does using the input.', 'Call it several times with different sizes.', 'Replace duplicated code with your block.'],
    challenge: 'Refactor one of your games to use at least one custom block with an input.', skills: ['Functions', 'Reusability', 'Refactoring'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'A "My Block" (custom block) is like a:', options: ['function you can reuse', 'sprite', 'backdrop', 'sound'], answerIndex: 0 },
      { question: 'Giving a custom block an input lets you:', options: ['use it with different values', 'change the stage', 'add a score', 'play music'], answerIndex: 0 },
      { question: 'Replacing repeated code with a custom block is called:', options: ['refactoring', 'deleting', 'broadcasting', 'cloning'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'predict', title: '🔮 Predict', code: 'define greet (name)\n  say (join "Hi " (name))\n\ngreet ["Sara"]', question: 'What does the sprite say?', options: ['Hi name', 'Hi Sara', 'name', 'nothing'], answerIndex: 1, explanation: 'The input "name" is replaced by "Sara".' }],
  },
  { id: 'sc-11', title: 'Capstone: Design & Share a Project', emoji: '🚀', difficulty: 4, ageGroup: '10-12', level: 'Advanced', moduleId: 'sc-m3', moduleTitle: L3, order: 11,
    concept: 'the full design + publish process', conceptExplain: 'Students plan, build, test and publish an original Scratch project (game, animation or interactive story), then share it to the Scratch community and get feedback.',
    objectives: ['Plan an original project', 'Build, test and debug it', 'Publish/share and gather feedback'],
    steps: ['Pick a project type and storyboard it.', 'Build it using variables/loops/conditionals/clones.', 'Test and debug.', 'Share it and write project notes/credits.'],
    challenge: 'Publish a polished project with instructions, then improve it from one piece of feedback.', skills: ['Design Process', 'Publishing', 'Iteration'], materials: M(''), resources: [SCRATCH],
    quiz: [
      { question: 'Before building a big project you should:', options: ['plan/storyboard it', 'publish it', 'delete sprites', 'mute sounds'], answerIndex: 0 },
      { question: 'Fixing problems in your code is called:', options: ['debugging', 'broadcasting', 'cloning', 'hosting'], answerIndex: 0 },
      { question: 'Improving a project after feedback is called:', options: ['iterating', 'deleting', 'ignoring', 'starting over'], answerIndex: 0 },
    ],
    interactions: [{ kind: 'match', title: '🔗 Match the step', pairs: [{ left: 'Storyboard', right: 'Plan the project' }, { left: 'Build with blocks', right: 'Create it' }, { left: 'Test & fix', right: 'Debug' }, { left: 'Share + feedback', right: 'Publish & iterate' }] }],
  },
];

export const SCRATCH_LESSONS: LessonDetail[] = C.map(c => makeKitLesson(c, P));
export const SCRATCH_COURSE: Course = {
  id: P.courseId, slug: 'code-games-and-stories', title: P.courseTitle, programId: P.programId, programSlug: P.programSlug,
  ageGroup: '8-9', level: 'Beginner',
  description: 'Code games, animations and interactive stories with Scratch (scratch.mit.edu). Level I: sprites, motion, loops, events and stories. Level II: variables, conditionals, collisions, complete games and clones. Level III: lists, custom blocks, and a publish-and-share capstone. Every lesson has a quiz and a hands-on activity.',
  objectives: ['Build programs with sequences, loops, events and broadcasts', 'Use variables, conditionals and collision detection', 'Build complete games with scoring and win/lose', 'Use lists and custom blocks', 'Design, publish and iterate an original project'],
  duration: '11 lessons × 45–60 minutes', totalHours: 11, lessonCount: 11, prerequisites: [],
  skills: ['Scratch', 'Game Design', 'Variables & Logic', 'Lists', 'Functions'],
  modules: [
    { id: 'sc-m1', title: L1, order: 1, description: 'Sprites, motion, looks, loops, events and a first animation/story.', lessons: C.filter(c => c.moduleId === 'sc-m1').map(kitSummary) },
    { id: 'sc-m2', title: L2, order: 2, description: 'Variables, conditionals, collisions, a complete game, and clones.', lessons: C.filter(c => c.moduleId === 'sc-m2').map(kitSummary) },
    { id: 'sc-m3', title: L3, order: 3, description: 'Lists, custom blocks, and a design-and-publish capstone.', lessons: C.filter(c => c.moduleId === 'sc-m3').map(kitSummary) },
  ],
};
