import type { Course, LessonDetail } from '@/types';
import { SCRATCH_CHAPTER_MODULE } from './school-chapters';

// ─── Complete Scratch Jr Course: "My First Stories" ──────────────
export const SCRATCH_JR_COURSE: Course = {
  id: 'scratch-jr-beginners',
  slug: 'my-first-stories',
  title: 'My First Stories with Scratch Jr',
  programId: 'scratch-jr',
  programSlug: 'scratch-jr',
  ageGroup: '6-7',
  level: 'Beginner',
  description:
    'Students discover Scratch Jr through creative storytelling. Over 8 fun sessions they learn to add characters, make them move and talk, build scenes, and share their own interactive stories.',
  objectives: [
    'Open and navigate the Scratch Jr app confidently',
    'Add characters, backgrounds, and sounds to a project',
    'Use movement, speech, size, and speed blocks',
    'Understand the concept of sequences and simple loops',
    'Create and present a complete animated story',
  ],
  duration: '20 sessions × 30–45 minutes',
  totalHours: 12,
  lessonCount: 20,
  prerequisites: [],
  skills: ['Sequencing', 'Visual Coding', 'Storytelling', 'Creativity', 'Problem Solving'],
  modules: [
    {
      id: 'sjb-m1',
      title: 'Module 1: Warm-Up (Practice)',
      description: 'Two guided practice lessons to get comfortable with the app (suggested starter content).',
      order: 1,
      lessons: [
        { id: 'sjb-l1', title: 'Welcome to Scratch Jr!', duration: '45 min', difficulty: 1, skills: ['App Navigation', 'Exploration'],   order: 1 },
        { id: 'sjb-l2', title: 'My First Character',      duration: '45 min', difficulty: 1, skills: ['Sprites', 'Stage', 'Drag & Drop'], order: 2 },
      ],
    },
    {
      id: 'sjr-m1',
      title: 'Module 2: Make Things Move (Video Tutorials)',
      description: 'Follow the video tutorials to move characters, change size & speed, and draw your own.',
      order: 2,
      lessons: [
        { id: 'sjr-v1', title: 'Make a Character Move',  duration: '30–45 min', difficulty: 1, skills: ['Motion Blocks'], order: 3 },
        { id: 'sjr-v2', title: 'Move Two Characters',    duration: '30–45 min', difficulty: 1, skills: ['Sprites'],       order: 4 },
        { id: 'sjr-v3', title: 'Change Size and Speed',  duration: '30–45 min', difficulty: 1, skills: ['Looks', 'Speed'], order: 5 },
        { id: 'sjr-v4', title: 'Code Movement',          duration: '30–45 min', difficulty: 1, skills: ['Sequencing'],    order: 6 },
        { id: 'sjr-v5', title: 'Use the Paint Editor',   duration: '30–45 min', difficulty: 1, skills: ['Paint Editor'],  order: 7 },
      ],
    },
    {
      id: 'sjr-m2',
      title: 'Module 3: Build Mini-Games (Video Tutorials)',
      description: 'Build simple games — basketball, memory, maze, and more.',
      order: 3,
      lessons: [
        { id: 'sjr-v6',  title: 'Make a Basketball Game',          duration: '30–45 min', difficulty: 2, skills: ['Game Design'], order: 8 },
        { id: 'sjr-v7',  title: 'Make a Memory Game',              duration: '30–45 min', difficulty: 2, skills: ['Game Design'], order: 9 },
        { id: 'sjr-v8',  title: 'Maze Game with Messages',         duration: '30–45 min', difficulty: 2, skills: ['Messages'],    order: 10 },
        { id: 'sjr-v9',  title: 'Knock-Knock Joke (Camera & Mic)', duration: '30–45 min', difficulty: 2, skills: ['Sound', 'Camera'], order: 11 },
        { id: 'sjr-v10', title: 'Among Us in ScratchJr',           duration: '30–45 min', difficulty: 2, skills: ['Game Design'], order: 12 },
        { id: 'sjr-v11', title: 'Hide & Seek',                     duration: '30–45 min', difficulty: 2, skills: ['Hide/Show'],   order: 13 },
      ],
    },
    {
      id: 'sjr-m3',
      title: 'Module 4: Create & Share (Video Tutorials)',
      description: 'Change looks, explore sample projects, and build a jumping game.',
      order: 4,
      lessons: [
        { id: 'sjr-v12', title: 'Change Looks',        duration: '30–45 min', difficulty: 3, skills: ['Looks'],       order: 14 },
        { id: 'sjr-v13', title: 'Use Sample Projects', duration: '30–45 min', difficulty: 3, skills: ['Exploration'], order: 15 },
        { id: 'sjr-v14', title: 'Move Characters',     duration: '30–45 min', difficulty: 3, skills: ['Motion'],      order: 16 },
        { id: 'sjr-v15', title: 'Make a Jumping Game', duration: '30–45 min', difficulty: 3, skills: ['Game Design'], order: 17 },
      ],
    },
    SCRATCH_CHAPTER_MODULE,
  ],
};

// ─── Lesson 1: Full Detail ────────────────────────────────────────
export const SCRATCH_JR_LESSON_1: LessonDetail = {
  id: 'sjb-l1',
  slug: 'welcome-to-scratch-jr',
  title: 'Welcome to Scratch Jr!',
  programId: 'scratch-jr',
  programSlug: 'scratch-jr',
  programTitle: 'Scratch Jr',
  programColor: '#8B5CF6',
  courseId: 'scratch-jr-beginners',
  courseTitle: 'My First Stories with Scratch Jr',
  moduleId: 'sjb-m1',
  moduleTitle: 'Module 1: Getting to Know Scratch Jr',
  ageGroup: '6-7',
  level: 'Beginner',
  duration: '45 minutes',
  difficulty: 1,
  skills: ['App Navigation', 'Exploration', 'Following Instructions', 'Curiosity'],
  materials: [
    { item: 'iPad or Android tablet',                     quantity: '1 per student or pair' },
    { item: 'Scratch Jr app',                             quantity: 'Pre-installed' },
    { item: 'Whiteboard and colorful markers',            quantity: '1 per classroom' },
    { item: '"Parts of Scratch Jr" poster',               quantity: '1 per classroom',       isOptional: true },
    { item: 'Sticker reward sheet',                       quantity: '1 per student',          isOptional: true },
    { item: 'Pencil and blank paper (for drawing robot)', quantity: '1 per student',          isOptional: true },
  ],
  objectives: [
    'Open the Scratch Jr app and create a new project.',
    'Identify the main areas: Stage, Character area, Block area, Scripts area.',
    'Add at least one character (sprite) to the stage.',
    'Tap the green flag to run a script.',
    'Feel excited and curious about Scratch Jr!',
  ],
  assessmentChecklist: [
    'Student can open Scratch Jr and create a new project independently.',
    'Student can name and point to the Stage, Characters, Blocks, and Scripts.',
    'Student added at least one character to their project.',
    'Student tapped the green flag and observed something happen.',
    'Student described one thing they want to make in the next lesson.',
  ],
  quiz: [
    { question: 'In Scratch Jr, the character you control is called a:', options: ['Sprite', 'Button', 'Page', 'Brush'], answerIndex: 0 },
    { question: 'What do you tap to make your project start/play?', options: ['the green flag', 'the red circle', 'the home button', 'the camera'], answerIndex: 0 },
    { question: 'You make the sprite do things by:', options: ['joining blocks together', 'typing words', 'drawing only', 'singing'], answerIndex: 0 },
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Turn on all tablets and open the Scratch Jr app on each one.',
        'Create a simple demo project in advance: a cat that walks across the screen when you tap the green flag. Be ready to show this at the start.',
        'Draw or print a "Parts of Scratch Jr" diagram on the whiteboard (Stage, Characters, Blocks, Scripts).',
        'Set up the sticker reward chart on the wall.',
        'Read the Troubleshooting section below — new students often struggle with tapping vs. dragging.',
        'Have the "Scratch Jr Interface" PDF open on your own device as a reference.',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'Warm-up (5 min): Ask "Has anyone ever made a computer game or animation before?" Let 2–3 students share. Say: "Today we\'re going to explore a magical app where YOU are the programmer!"',
          tip: 'Keep energy high. Enthusiasm is contagious at this age.',
        },
        {
          step: 2,
          instruction: 'Show Your Demo (5 min): Open your demo project. Tap the green flag and let the cat walk. Ask "What do you see? What do you think made it move?" Take 2–3 answers.',
          coachNote: 'Do NOT explain the blocks yet — let them wonder. This builds curiosity.',
        },
        {
          step: 3,
          instruction: 'Introduce the App (5 min): Point to each area on the whiteboard diagram. Name them one by one: "This is the STAGE — like a theatre stage. This is the CHARACTER AREA — these are our actors..."',
          tip: 'Use theatre/stage analogy — most kids understand what a stage is from school plays.',
        },
        {
          step: 4,
          instruction: 'Explore Together (10 min): Students open Scratch Jr. Walk around the room. Say "Find the Stage. Now find the Characters. Now find the green flag and tap it." Keep instructions short and one at a time.',
          tip: 'Go slow. Wait until 80% of the class has done it before moving on.',
          coachNote: 'If a student is very fast, give them the challenge: "Can you find where to change the background?"',
        },
        {
          step: 5,
          instruction: 'Add a New Project (5 min): Guide all students: tap the house icon → tap the "+" to create a new project → tap the cat character that appears. Ask "What does the cat look like? What name do you want to give it?"',
        },
        {
          step: 6,
          instruction: 'Free Explore (10 min): Say "Now explore! Tap things, drag blocks around — there are no mistakes!" Walk around, narrate what you see: "Oh, I see Omar made the cat grow! How did you do that?"',
          tip: 'Narrate discoveries to the class — this teaches indirectly and celebrates students.',
        },
        {
          step: 7,
          instruction: 'Wrap-Up (5 min): Gather attention. Ask "Who can show me ONE thing they discovered?" Let 2–3 students share (hold up the tablet or describe). Award stickers. Preview next lesson.',
          coachNote: 'End on a high note. Say "Next time, we\'ll make our characters actually MOVE and do amazing things!"',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission Today! 🚀',
      emoji: '🎯',
      studentTitle: 'Your Mission Today! 🚀',
      content: [
        'Turn on your tablet and open Scratch Jr.',
        'Find the Stage, the Characters, and the Blocks — can you spot all 3?',
        'Tap the green flag and see what happens!',
        'Create a NEW project by tapping the house, then the + button.',
        'Add your favourite character to the stage.',
        'Explore! Tap everything! Nothing will break, we promise 😊',
        'Find ONE cool thing and be ready to share it!',
      ] as string[],
      studentContent: [
        '🟢 Open Scratch Jr on your tablet',
        '👀 Find the Stage, Characters, and Blocks',
        '🚩 Tap the green flag!',
        '✨ Make a NEW project',
        '🐱 Add your favourite character',
        '🔍 Explore — nothing will break!',
        '⭐ Find something cool to share!',
      ],
    },
    {
      type: 'activity',
      title: 'Main Activity: Explorer Mission',
      emoji: '🗺️',
      content: [
        'Give each student a piece of paper. Tell them to draw their favourite part of Scratch Jr (the cat, the stage, the blocks — whatever they liked most).',
        'Under the drawing, write or dictate: "In Scratch Jr I can..."',
        'Students who finish early can add colour or draw what they want to make next time.',
      ] as string[],
      studentContent: [
        'Draw your favourite thing from Scratch Jr today!',
        'Write (or ask your coach to write): "In Scratch Jr I can..."',
        'Colour it in and make it amazing! 🎨',
      ],
    },
    {
      type: 'challenge',
      title: 'Challenge: The Scavenger Hunt',
      emoji: '🔍',
      content: [
        'Can you find these in the app? Tap each one when you find it:',
        '• The green flag button',
        '• The red stop button',
        '• The "Change Background" button (hint: it looks like a picture)',
        '• The delete button (looks like scissors)',
        '• The paint tool (to draw your own character!)',
      ] as string[],
      studentContent: [
        '🟢 Find the GREEN FLAG',
        '🔴 Find the RED STOP button',
        '🖼️ Find "Change Background"',
        '✂️ Find the Delete button',
        '🎨 Find the Paint tool',
      ],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Fast Finishers',
      emoji: '🌟',
      content: [
        'You found everything? Amazing! Now try this:',
        '1. Tap the paint brush to create YOUR OWN character by drawing it.',
        '2. Add it to the stage next to the cat.',
        '3. Tap the green flag — what happens to your drawing?',
        '4. Bonus: Can you figure out how to make your drawing MOVE? (Hint: look at the yellow blocks!)',
      ] as string[],
      studentContent: [
        '🎨 Draw your OWN character using the paint brush!',
        '🎭 Add it to the stage with the cat',
        '🚩 Tap the green flag and see what happens!',
        '🔮 BONUS: Can you make YOUR character move?',
      ],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Student accidentally deleted their character',
          cause: 'The trash/scissors icon is close to other buttons — easy to tap by mistake',
          solution: 'Tap the undo arrow at the top of the screen. If not available, show student how to add a character again from the "+" button in the character area.',
        },
        {
          problem: 'App crashes or freezes',
          cause: 'Too many tabs open or device is low on memory',
          solution: 'Close other apps, restart Scratch Jr. Projects auto-save, so nothing is lost.',
        },
        {
          problem: 'Student cannot drag blocks to the scripts area',
          cause: 'Tablets sometimes require a longer press before dragging at this age',
          solution: 'Demonstrate slowly: press and hold (1 second), then drag. Practice with the student using a physical drag on the table first.',
        },
        {
          problem: 'Student is overwhelmed or frustrated',
          cause: 'Too much novelty at once',
          solution: 'Sit next to them. Ask "What\'s the last thing that worked?" Go back to that point. Keep interactions to one step at a time.',
        },
        {
          problem: 'Multiple students at very different levels',
          cause: 'Natural variation in prior exposure to technology',
          solution: 'Pair fast finishers with slower ones as "helpers". This benefits both — teaching reinforces learning.',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment',
      emoji: '✅',
      content: [
        'Can the student open Scratch Jr and navigate to the home screen?',
        'Can the student create a new project?',
        'Can the student identify the Stage, Character area, and Blocks?',
        'Did the student successfully add a character?',
        'Did the student discover something independently and share it?',
        'Did the student show enjoyment and curiosity?',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice Activity',
      emoji: '🏠',
      content: [
        'If students have access to a tablet at home: Ask them to open Scratch Jr and show a family member what they learned today.',
        'If no tablet at home: Students can draw a picture of the "Scratch Jr stage" with a character on it, and plan what story they want to tell next time.',
        'Optional family challenge: "Ask a family member — what would a robot do if it could only move forward and backward?"',
      ] as string[],
      studentContent: [
        '📱 If you have a tablet: Show a family member Scratch Jr!',
        '🎨 If no tablet: Draw the Scratch Jr stage and your favourite character!',
        '💬 Ask your family: "If you had a robot, what would you make it do?"',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'ENERGY LEVEL: This lesson should feel like playtime. Resist the urge to over-teach — exploration is the learning.',
        'COMMON WIN: Kids love discovering the paint brush to draw their own characters. If time allows, let them do this — it massively increases engagement.',
        'RED FLAG: If more than 3 students seem confused about what to tap, slow down and do "follow me" — everyone watches and copies you step by step.',
        'NEXT LESSON PREVIEW: Lesson 2 introduces movement blocks. Consider sending home a parent note about Scratch Jr and encouraging practice at home.',
        'DIFFERENTIATION: Students with more tech experience will race ahead. Have them explain to a neighbour instead of moving to harder tasks — explaining consolidates their own understanding.',
        'TIME CHECK: The 10-minute free explore is the most valuable. Don\'t cut it short. You can shorten the warm-up if needed.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'sjl1-r1', title: 'ScratchJr Interface Guide (official)',   type: 'link',      audience: 'coach',   url: 'https://www.scratchjr.org/learn.html',      description: 'Interface, paint editor & block guides — print for the classroom' },
    { id: 'sjl1-r2', title: 'Official ScratchJr Activities (worksheets)', type: 'link',  audience: 'both',    url: 'https://www.scratchjr.org/teach.html',      description: 'Free official activity sheets to use in class' },
    { id: 'sjl1-r3', title: 'ScratchJr Block Reference (official)',   type: 'link',      audience: 'both',    url: 'https://www.scratchjr.org/learn.html',      description: 'Every block explained — the classroom reference' },
    { id: 'sjl1-r4', title: 'Getting Started Video — Scratch Jr',     type: 'video',     audience: 'coach',   url: 'https://www.scratchjr.org',                 description: 'Official intro video',            needsReview: true },
    { id: 'sjl1-r5', title: 'ScratchJr Curricula for Coaches (official)', type: 'link',  audience: 'coach',   url: 'https://www.scratchjr.org/teach.html',      description: 'Full free curricula (Animated Genres, Playground games) to demo from' },
  ],
};

// ─── Lesson 2: Full Detail ────────────────────────────────────────
export const SCRATCH_JR_LESSON_2: LessonDetail = {
  id: 'sjb-l2',
  slug: 'my-first-character',
  title: 'My First Character',
  programId: 'scratch-jr',
  programSlug: 'scratch-jr',
  programTitle: 'Scratch Jr',
  programColor: '#8B5CF6',
  courseId: 'scratch-jr-beginners',
  courseTitle: 'My First Stories with Scratch Jr',
  moduleId: 'sjb-m1',
  moduleTitle: 'Module 1: Getting to Know Scratch Jr',
  ageGroup: '6-7',
  level: 'Beginner',
  duration: '45 minutes',
  difficulty: 1,
  skills: ['Sprites', 'Stage', 'Character Selection', 'Drag & Drop', 'Size Control'],
  materials: [
    { item: 'iPad or Android tablet', quantity: '1 per student or pair' },
    { item: 'Scratch Jr app',         quantity: 'Pre-installed' },
    { item: 'Whiteboard',             quantity: '1' },
    { item: 'Character cards printed',quantity: '1 set',  isOptional: true },
  ],
  objectives: [
    'Add multiple characters to a project.',
    'Delete characters they don\'t want.',
    'Resize a character using the grow and shrink blocks.',
    'Position characters anywhere on the stage using drag and drop.',
    'Begin to understand that characters are the "actors" in their stories.',
  ],
  assessmentChecklist: [
    'Student added at least 2 different characters to the stage.',
    'Student successfully deleted a character.',
    'Student made a character larger and smaller using blocks.',
    'Student positioned characters in different areas of the stage.',
    'Student can explain: "What is a character in Scratch Jr?"',
  ],
  sections: [
    {
      type: 'coach_prep',
      title: 'Before-Class Preparation',
      emoji: '📋',
      isCoachOnly: true,
      content: [
        'Open Scratch Jr on all tablets and start a new blank project on each.',
        'Prepare a demo showing: 3 different characters on stage, one very big and one very small.',
        'Write on whiteboard: GROW block (yellow arrow up), SHRINK block (yellow arrow down), RESET SIZE block.',
        'If using printed Character Cards, lay them out on tables so students can "pick" their characters before using the app.',
      ] as string[],
    },
    {
      type: 'coach_steps',
      title: 'Step-by-Step Coach Instructions',
      emoji: '🎓',
      isCoachOnly: true,
      content: [
        {
          step: 1,
          instruction: 'Recall (5 min): "Last time we visited Scratch Jr. Who can remember ONE thing we found?" Take 3 answers. Quickly show the app areas again on the whiteboard.',
          tip: 'Keep review fast — students are eager to use the tablets again.',
        },
        {
          step: 2,
          instruction: 'Introduce Characters (5 min): Show your demo project. Say "A character is the ACTOR in your story. In Scratch Jr, they\'re called SPRITES. Today we\'re going to pick our cast!" Point to each character on stage.',
        },
        {
          step: 3,
          instruction: 'Guided: Add a Character (10 min): Everyone follows along. Tap the "+" in the Character Area → choose a character → tap to add. Ask: "What character did you choose and WHY?" Let 3 students answer.',
          coachNote: 'This is a key moment — let students choose freely. Choice = ownership = engagement.',
        },
        {
          step: 4,
          instruction: 'Grow & Shrink (10 min): Go to the Yellow Looks blocks. Show the grow (up arrow) and shrink (down arrow) blocks. "Drag GROW to the scripts area. Tap the block. What happened?!" Let them experiment.',
          tip: 'Some students will make characters enormous or tiny — celebrate this. "Look how BIG Omar\'s elephant is!"',
        },
        {
          step: 5,
          instruction: 'Delete & Add Again (5 min): "Every actor needs a ROLE. If your character doesn\'t fit your story, you can remove them." Show how to hold on a character → trash icon appears. Then add a new one.',
        },
        {
          step: 6,
          instruction: 'Creative Time (10 min): "Now set up YOUR stage. Add the characters for your story. Make them the right size. Put them where you want them."',
          coachNote: 'Walk around, ask "What story is this going to be about?" — this primes Lesson 5–7.',
        },
      ],
    },
    {
      type: 'student_steps',
      title: 'Your Mission: Build Your Cast! 🎭',
      emoji: '🎯',
      content: [
        '1. Open Scratch Jr and start a new project.',
        '2. Tap the + button in the Character Area.',
        '3. Choose your favourite character and add it!',
        '4. Now add a second character — someone for the first one to talk to!',
        '5. Find the yellow LOOKS blocks — try GROW and SHRINK.',
        '6. Move your characters by dragging them around the stage.',
        '7. Imagine: what story will these characters tell?',
      ] as string[],
    },
    {
      type: 'activity',
      title: 'Main Activity: Casting Your Story',
      emoji: '🎬',
      content: [
        'Students choose 2–4 characters for their story.',
        'They position them on the stage and adjust sizes (big character = important character).',
        'Students tell the coach: "This is [character name] and they are going to [action]."',
        'Coach writes each student\'s story idea on a sticky note for later lessons.',
      ] as string[],
    },
    {
      type: 'challenge',
      title: 'Challenge: The Perfect Stage',
      emoji: '⭐',
      content: [
        'Create a scene with EXACTLY:',
        '• 1 BIG character (the hero)',
        '• 1 MEDIUM character (the friend)',
        '• 1 TINY character (the funny surprise)',
        'Position them on different parts of the stage.',
        'Give each character a name (tap and hold → rename).',
      ] as string[],
    },
    {
      type: 'extra_challenge',
      title: 'Extra Challenge: Draw Your Own Character',
      emoji: '🌟',
      content: [
        'The Scratch Jr library has lots of characters — but yours will be UNIQUE.',
        '1. Tap "+" in Characters → tap the paintbrush icon.',
        '2. Draw YOUR OWN character using the tools.',
        '3. Colour it in.',
        '4. Add it to the stage with the others.',
        'Tip: Draw something from YOUR story — a house, a dragon, a spaceship!',
      ] as string[],
    },
    {
      type: 'troubleshooting',
      title: 'Common Problems & Solutions',
      emoji: '🔧',
      isCoachOnly: true,
      content: [
        {
          problem: 'Student can\'t delete a character',
          cause: 'The tap-and-hold needed to get the trash icon requires timing',
          solution: 'Show them: press and HOLD for 1 full second until the trash can appears. Practice on an object first.',
        },
        {
          problem: 'Character disappears off the stage edge',
          cause: 'Students drag characters too far',
          solution: 'Characters can be dragged back from the edge. Show student how to find them by scrolling or reducing size first.',
        },
        {
          problem: 'Student wants to use a character that\'s not in the library',
          cause: 'Creative vision exceeds library options',
          solution: 'Direct to the paint tool. This is a GREAT opportunity — the student just had a creative idea!',
        },
      ],
    },
    {
      type: 'assessment',
      title: 'Assessment',
      emoji: '✅',
      content: [
        'Added 2+ characters to a project.',
        'Successfully deleted at least one character.',
        'Used grow and/or shrink blocks.',
        'Can explain what a character (sprite) is in their own words.',
        'Has started thinking about their story topic.',
      ] as string[],
    },
    {
      type: 'homework',
      title: 'Practice',
      emoji: '🏠',
      content: [
        'Draw a picture of your story characters on paper.',
        'Give each character a name and decide: what will they do in your story?',
        'Bonus: practice telling your story OUT LOUD to a family member tonight!',
      ] as string[],
      studentContent: [
        '✏️ Draw your story characters on paper!',
        '💬 Give them names',
        '🗣️ Tell your story OUT LOUD to your family tonight!',
      ],
    },
    {
      type: 'coach_notes',
      title: 'Coach Notes (Private)',
      emoji: '📝',
      isCoachOnly: true,
      content: [
        'STORY PLANNING: The sticky note idea in the main activity is genuinely useful — refer back to these in Lesson 7 (My Story Project).',
        'CREATIVE BLOCK: Some students have trouble deciding which character to choose. Give them a context: "If your story was about going on an adventure, who would you bring?"',
        'TABLET SHARING: If students share tablets, rotate who is "the driver" every 10 minutes. The non-driver should suggest what to do.',
        'PARENT COMMUNICATION: Consider sending a note home with a screenshot of each student\'s stage — parents love seeing what their kids built.',
      ] as string[],
    },
  ],
  resources: [
    { id: 'sjl2-r1', title: 'Official ScratchJr Activities (worksheets)', type: 'link', audience: 'student', url: 'https://www.scratchjr.org/teach.html', description: 'Free official activity sheets — pick a character activity' },
    { id: 'sjl2-r2', title: 'ScratchJr Paint Editor Guide (official)',    type: 'link', audience: 'coach',   url: 'https://www.scratchjr.org/learn.html', description: 'How to edit and create characters' },
    { id: 'sjl2-r3', title: 'ScratchJr Curricula — story planning (official)', type: 'link', audience: 'coach', url: 'https://www.scratchjr.org/teach.html', description: 'The Animated Genres curriculum includes story-planning sheets' },
    { id: 'sjl2-r4', title: 'ScratchJr — Official Site (free activities & curricula)', type: 'link', audience: 'both', url: 'https://www.scratchjr.org', description: 'Free official ScratchJr activities and teacher curricula' },
  ],
};

// ─── Lessons 3–8: Summary data (full details added as content is created) ──
export const SCRATCH_JR_LESSON_SUMMARIES = [
  {
    id: 'sjb-l3',
    slug: 'lets-move',
    title: 'Let\'s Move!',
    overview: 'Students use blue Movement blocks to make characters walk, run, jump, and turn.',
    keyBlocks: ['Move Right', 'Move Left', 'Move Up', 'Move Down', 'Turn'],
    suggestedActivities: ['Obstacle course race', 'Follow-the-leader coding'],
    status: 'draft',
  },
  {
    id: 'sjb-l4',
    slug: 'jump-and-repeat',
    title: 'Jump and Repeat',
    overview: 'Introduce the Repeat/Loop block. Students make characters bounce, spin continuously, and follow repeating patterns.',
    keyBlocks: ['Repeat', 'End (stop)', 'Speed blocks'],
    suggestedActivities: ['Spinning top challenge', 'Bouncing ball animation'],
    status: 'draft',
  },
  {
    id: 'sjb-l5',
    slug: 'say-something',
    title: 'Say Something!',
    overview: 'Add speech bubbles to characters. Students write simple dialogue between characters to start telling stories.',
    keyBlocks: ['Say block', 'Wait block'],
    suggestedActivities: ['Comic strip conversation', 'Two characters greeting each other'],
    status: 'draft',
  },
  {
    id: 'sjb-l6',
    slug: 'change-the-scene',
    title: 'Change the Scene',
    overview: 'Students add background scenes and create multiple pages, learning how stories flow from scene to scene.',
    keyBlocks: ['Change Scene', 'Page navigation'],
    suggestedActivities: ['3-scene story', 'Journey from home to adventure'],
    status: 'draft',
  },
  {
    id: 'sjb-l7',
    slug: 'my-story-project',
    title: 'My Story Project',
    overview: 'Full lesson dedicated to completing a personal story project. Combines all skills: characters, movement, speech, scenes.',
    keyBlocks: ['All previously learned blocks'],
    suggestedActivities: ['Complete story project', 'Peer support pairs'],
    status: 'draft',
  },
  {
    id: 'sjb-l8',
    slug: 'share-our-stories',
    title: 'Share Our Stories',
    overview: 'Celebration session. Students present their stories, give kind feedback, and earn their first badges.',
    keyBlocks: ['Review all'],
    suggestedActivities: ['Story festival', 'Badge ceremony', 'Parent showcase'],
    status: 'draft',
  },
];

export const SCRATCH_JR_LESSONS_MAP: Record<string, LessonDetail> = {
  'sjb-l1': SCRATCH_JR_LESSON_1,
  'sjb-l2': SCRATCH_JR_LESSON_2,
};
